# Secure-analyzer-specific configuration
# Inherits from shared base_config.yaml

# Override server port for secure-analyzer
server:
  port: 5070

# Secure-analyzer specific policy settings
policy:
  secure_only_models: ${SECURE_ONLY_MODELS:-bedrock,ollama}
  all_providers: ${ALL_PROVIDERS:-bedrock,ollama,openai,anthropic,grok}
  default_prompt: |
    Summarize focusing on risks, PII, secrets, and client information.

# Circuit breaker settings
circuit_breaker:
  max_failures: ${SECURE_ANALYZER_CIRCUIT_BREAKER_MAX_FAILURES:-5}
  timeout_seconds: ${SECURE_ANALYZER_CIRCUIT_BREAKER_TIMEOUT:-60}

# Service URLs
services:
  summarizer_hub_url: ${SUMMARIZER_HUB_URL:-http://summarizer-hub:5060}

# Testing configuration
testing: ${TESTING:-false}
