# Individual Docker Compose for Secure Analyzer Service
# This allows the secure-analyzer to run independently as a standalone service

version: "3.9"

services:
  secure-analyzer:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ../../:/app:ro
      - ./:/app/services/secure-analyzer:rw
      - ../../:/app:ro
    environment:
      - ENVIRONMENT=development
    command: bash -lc "pip install --no-cache-dir fastapi uvicorn httpx pydantic && python services/secure-analyzer/main.py"
    ports:
      - "5070:5070"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5070/health"]
      interval: 30s
      timeout: 10s
      retries: 3
