"""Runtime Process Monitoring Service for memory leak detection and performance monitoring.

Provides comprehensive runtime monitoring including:
- Memory leak detection with trend analysis
- CPU usage monitoring and alerting
- Thread monitoring and deadlock detection
- Resource usage tracking and limits
- Performance profiling and bottleneck detection
- Automatic cleanup and optimization recommendations
"""
import asyncio
import gc
import psutil
import threading
import time
import tracemalloc
import logging
from typing import Dict, Any, List, Optional, Callable, Tuple
from dataclasses import dataclass, field
from enum import Enum
from collections import defaultdict, deque
import resource
import sys


logger = logging.getLogger(__name__)


class ResourceType(Enum):
    """Types of resources to monitor."""
    MEMORY = "memory"
    CPU = "cpu"
    THREADS = "threads"
    FILE_DESCRIPTORS = "file_descriptors"
    NETWORK_CONNECTIONS = "network_connections"
    DISK_IO = "disk_io"


class AlertSeverity(Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    EMERGENCY = "emergency"


@dataclass
class ResourceThreshold:
    """Threshold configuration for resource monitoring."""
    warning_threshold: float
    critical_threshold: float
    emergency_threshold: float
    measurement_unit: str = ""


@dataclass
class ResourceMeasurement:
    """A single resource measurement."""
    timestamp: float
    value: float
    resource_type: ResourceType
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ResourceTrend:
    """Trend analysis for resource usage."""
    resource_type: ResourceType
    measurements: deque = field(default_factory=lambda: deque(maxlen=100))
    slope: float = 0.0  # Rate of change
    last_updated: float = 0.0

    def add_measurement(self, measurement: ResourceMeasurement) -> None:
        """Add a measurement and update trend analysis."""
        self.measurements.append(measurement)

        if len(self.measurements) >= 2:
            # Calculate simple linear regression slope
            n = len(self.measurements)
            x_values = [i for i in range(n)]
            y_values = [m.value for m in self.measurements]

            sum_x = sum(x_values)
            sum_y = sum(y_values)
            sum_xy = sum(x * y for x, y in zip(x_values, y_values))
            sum_xx = sum(x * x for x in x_values)

            if n * sum_xx - sum_x * sum_x != 0:
                self.slope = (n * sum_xy - sum_x * sum_y) / (n * sum_xx - sum_x * sum_x)

        self.last_updated = time.time()

    def get_average(self) -> float:
        """Get average value."""
        if not self.measurements:
            return 0.0
        return sum(m.value for m in self.measurements) / len(self.measurements)

    def get_trend_description(self) -> str:
        """Get human-readable trend description."""
        if abs(self.slope) < 0.1:
            return "stable"
        elif self.slope > 0:
            return f"increasing (+{self.slope:.2f}/min)"
        else:
            return f"decreasing ({self.slope:.2f}/min)"


@dataclass
class MemorySnapshot:
    """Memory usage snapshot for leak detection."""
    timestamp: float
    total_memory: float
    python_memory: float
    gc_objects: int
    tracemalloc_stats: Optional[List] = None


@dataclass
class ProcessAlert:
    """Alert generated by process monitoring."""
    alert_id: str
    severity: AlertSeverity
    resource_type: ResourceType
    message: str
    current_value: float
    threshold_value: float
    timestamp: float
    recommendations: List[str] = field(default_factory=list)


class MemoryLeakDetector:
    """Advanced memory leak detection using multiple strategies."""

    def __init__(self, leak_threshold_mb: float = 50.0, growth_rate_threshold: float = 1.0):
        self.leak_threshold_mb = leak_threshold_mb
        self.growth_rate_threshold = growth_rate_threshold
        self.snapshots: List[MemorySnapshot] = []
        self.tracemalloc_enabled = False
        self._lock = threading.Lock()

        # Start tracemalloc for detailed analysis
        self._start_tracemalloc()

    def _start_tracemalloc(self) -> None:
        """Start tracemalloc for detailed memory analysis."""
        try:
            tracemalloc.start()
            self.tracemalloc_enabled = True
            logger.info("Tracemalloc started for memory leak detection")
        except Exception as e:
            logger.warning(f"Could not start tracemalloc: {e}")

    def take_snapshot(self) -> MemorySnapshot:
        """Take a memory usage snapshot."""
        process = psutil.Process()
        memory_info = process.memory_info()

        snapshot = MemorySnapshot(
            timestamp=time.time(),
            total_memory=memory_info.rss / 1024 / 1024,  # MB
            python_memory=psutil.virtual_memory().used / 1024 / 1024,  # MB
            gc_objects=len(gc.get_objects())
        )

        if self.tracemalloc_enabled:
            try:
                snapshot.tracemalloc_stats = tracemalloc.take_snapshot().statistics('lineno')
            except Exception as e:
                logger.debug(f"Could not take tracemalloc snapshot: {e}")

        with self._lock:
            self.snapshots.append(snapshot)
            # Keep only last 50 snapshots
            if len(self.snapshots) > 50:
                self.snapshots.pop(0)

        return snapshot

    def detect_leaks(self) -> List[ProcessAlert]:
        """Detect potential memory leaks."""
        alerts = []

        with self._lock:
            if len(self.snapshots) < 5:
                return alerts  # Need more data

            # Check for continuous growth
            recent_snapshots = self.snapshots[-10:]  # Last 10 snapshots
            memory_values = [s.python_memory for s in recent_snapshots]

            if len(memory_values) >= 2:
                growth = memory_values[-1] - memory_values[0]
                if growth > self.leak_threshold_mb:
                    alerts.append(ProcessAlert(
                        alert_id=f"memory_leak_{int(time.time())}",
                        severity=AlertSeverity.CRITICAL,
                        resource_type=ResourceType.MEMORY,
                        message=f"Potential memory leak detected: {growth:.1f}MB growth",
                        current_value=memory_values[-1],
                        threshold_value=self.leak_threshold_mb,
                        timestamp=time.time(),
                        recommendations=[
                            "Check for circular references",
                            "Review object creation patterns",
                            "Consider implementing object pooling",
                            "Run garbage collection manually: gc.collect()"
                        ]
                    ))

            # Check growth rate
            if len(recent_snapshots) >= 3:
                time_diffs = [s2.timestamp - s1.timestamp for s1, s2 in zip(recent_snapshots[:-1], recent_snapshots[1:])]
                growth_rates = [(m2 - m1) / t for (m1, m2), t in zip(zip(memory_values[:-1], memory_values[1:]), time_diffs)]

                avg_growth_rate = sum(growth_rates) / len(growth_rates)
                if avg_growth_rate > self.growth_rate_threshold:
                    alerts.append(ProcessAlert(
                        alert_id=f"memory_growth_rate_{int(time.time())}",
                        severity=AlertSeverity.WARNING,
                        resource_type=ResourceType.MEMORY,
                        message=f"High memory growth rate: {avg_growth_rate:.2f}MB/s",
                        current_value=avg_growth_rate,
                        threshold_value=self.growth_rate_threshold,
                        timestamp=time.time(),
                        recommendations=[
                            "Monitor memory allocation patterns",
                            "Check for memory-intensive operations",
                            "Consider memory profiling"
                        ]
                    ))

        return alerts

    def get_top_memory_consumers(self, limit: int = 10) -> List[Dict[str, Any]]:
        """Get top memory-consuming lines using tracemalloc."""
        if not self.tracemalloc_enabled:
            return []

        try:
            snapshot = tracemalloc.take_snapshot()
            stats = snapshot.statistics('lineno')

            top_consumers = []
            for stat in stats[:limit]:
                top_consumers.append({
                    "line": f"{stat.traceback[0].filename}:{stat.traceback[0].lineno}",
                    "size_mb": stat.size / 1024 / 1024,
                    "count": stat.count
                })

            return top_consumers
        except Exception as e:
            logger.debug(f"Could not get memory consumers: {e}")
            return []


class ThreadMonitor:
    """Monitor thread health and detect potential deadlocks."""

    def __init__(self):
        self.thread_states: Dict[str, Dict[str, Any]] = {}
        self.deadlock_threshold_seconds = 30.0

    def update_thread_states(self) -> None:
        """Update the state of all threads."""
        current_threads = {}

        for thread in threading.enumerate():
            thread_id = thread.ident
            current_threads[str(thread_id)] = {
                "name": thread.name,
                "daemon": thread.daemon,
                "alive": thread.is_alive(),
                "last_seen": time.time()
            }

        self.thread_states = current_threads

    def detect_dead_threads(self) -> List[ProcessAlert]:
        """Detect threads that may be deadlocked or hung."""
        alerts = []
        current_time = time.time()

        for thread_id, thread_info in self.thread_states.items():
            if not thread_info["alive"]:
                continue

            # Check if thread has been in the same state too long
            # This is a simple heuristic - in practice, you'd need more sophisticated deadlock detection
            time_since_last_update = current_time - thread_info["last_seen"]

            if time_since_last_update > self.deadlock_threshold_seconds:
                alerts.append(ProcessAlert(
                    alert_id=f"thread_deadlock_{thread_id}_{int(time.time())}",
                    severity=AlertSeverity.WARNING,
                    resource_type=ResourceType.THREADS,
                    message=f"Thread {thread_info['name']} may be deadlocked or hung",
                    current_value=time_since_last_update,
                    threshold_value=self.deadlock_threshold_seconds,
                    timestamp=current_time,
                    recommendations=[
                        "Check thread for infinite loops",
                        "Review synchronization primitives",
                        "Consider thread dump analysis"
                    ]
                ))

        return alerts

    def get_thread_summary(self) -> Dict[str, Any]:
        """Get summary of thread states."""
        total_threads = len(self.thread_states)
        daemon_threads = sum(1 for t in self.thread_states.values() if t["daemon"])
        alive_threads = sum(1 for t in self.thread_states.values() if t["alive"])

        return {
            "total_threads": total_threads,
            "daemon_threads": daemon_threads,
            "user_threads": total_threads - daemon_threads,
            "alive_threads": alive_threads,
            "dead_threads": total_threads - alive_threads
        }


class ProcessMonitorService:
    """Comprehensive process monitoring and alerting service."""

    def __init__(self):
        self.resource_thresholds = self._get_default_thresholds()
        self.resource_trends: Dict[ResourceType, ResourceTrend] = {}
        self.memory_detector = MemoryLeakDetector()
        self.thread_monitor = ThreadMonitor()

        self.alert_callbacks: List[Callable[[ProcessAlert], None]] = []
        self.measurement_interval = 10.0  # seconds
        self.monitoring_task: Optional[asyncio.Task] = None
        self._shutdown_event = asyncio.Event()

        # Initialize trends for all resource types
        for resource_type in ResourceType:
            self.resource_trends[resource_type] = ResourceTrend(resource_type)

    def _get_default_thresholds(self) -> Dict[ResourceType, ResourceThreshold]:
        """Get default resource thresholds."""
        return {
            ResourceType.MEMORY: ResourceThreshold(
                warning_threshold=512.0,  # MB
                critical_threshold=1024.0,  # MB
                emergency_threshold=2048.0,  # MB
                measurement_unit="MB"
            ),
            ResourceType.CPU: ResourceThreshold(
                warning_threshold=70.0,  # %
                critical_threshold=85.0,  # %
                emergency_threshold=95.0,  # %
                measurement_unit="%"
            ),
            ResourceType.THREADS: ResourceThreshold(
                warning_threshold=50,  # count
                critical_threshold=100,  # count
                emergency_threshold=200,  # count
                measurement_unit="threads"
            ),
            ResourceType.FILE_DESCRIPTORS: ResourceThreshold(
                warning_threshold=500,  # count
                critical_threshold=800,  # count
                emergency_threshold=1000,  # count
                measurement_unit="fds"
            ),
            ResourceType.NETWORK_CONNECTIONS: ResourceThreshold(
                warning_threshold=100,  # count
                critical_threshold=500,  # count
                emergency_threshold=1000,  # count
                measurement_unit="connections"
            )
        }

    def set_threshold(self, resource_type: ResourceType, threshold: ResourceThreshold) -> None:
        """Set custom threshold for a resource type."""
        self.resource_thresholds[resource_type] = threshold

    def add_alert_callback(self, callback: Callable[[ProcessAlert], None]) -> None:
        """Add callback for process alerts."""
        self.alert_callbacks.append(callback)

    def take_measurement(self, resource_type: ResourceType) -> float:
        """Take a measurement of the specified resource."""
        try:
            if resource_type == ResourceType.MEMORY:
                process = psutil.Process()
                return process.memory_info().rss / 1024 / 1024  # MB

            elif resource_type == ResourceType.CPU:
                return psutil.cpu_percent(interval=1.0)

            elif resource_type == ResourceType.THREADS:
                return threading.active_count()

            elif resource_type == ResourceType.FILE_DESCRIPTORS:
                try:
                    return len(psutil.Process().open_files())
                except (psutil.AccessDenied, AttributeError):
                    return 0

            elif resource_type == ResourceType.NETWORK_CONNECTIONS:
                try:
                    connections = psutil.Process().net_connections()
                    return len(connections)
                except (psutil.AccessDenied, AttributeError):
                    return 0

            elif resource_type == ResourceType.DISK_IO:
                io_counters = psutil.disk_io_counters()
                if io_counters:
                    return io_counters.read_bytes + io_counters.write_bytes
                return 0

        except Exception as e:
            logger.debug(f"Could not measure {resource_type.value}: {e}")
            return 0.0

        return 0.0

    def check_thresholds(self) -> List[ProcessAlert]:
        """Check all resource thresholds and generate alerts."""
        alerts = []

        for resource_type, threshold in self.resource_thresholds.items():
            measurement = self.take_measurement(resource_type)

            # Update trend
            measurement_obj = ResourceMeasurement(
                timestamp=time.time(),
                value=measurement,
                resource_type=resource_type
            )
            self.resource_trends[resource_type].add_measurement(measurement_obj)

            # Check thresholds
            severity = None
            threshold_value = None

            if measurement >= threshold.emergency_threshold:
                severity = AlertSeverity.EMERGENCY
                threshold_value = threshold.emergency_threshold
            elif measurement >= threshold.critical_threshold:
                severity = AlertSeverity.CRITICAL
                threshold_value = threshold.critical_threshold
            elif measurement >= threshold.warning_threshold:
                severity = AlertSeverity.WARNING
                threshold_value = threshold.warning_threshold

            if severity:
                alert = ProcessAlert(
                    alert_id=f"{resource_type.value}_{severity.value}_{int(time.time())}",
                    severity=severity,
                    resource_type=resource_type,
                    message=f"{resource_type.value.replace('_', ' ').title()} usage is {severity.value}: {measurement:.1f}{threshold.measurement_unit}",
                    current_value=measurement,
                    threshold_value=threshold_value,
                    timestamp=time.time(),
                    recommendations=self._get_recommendations(resource_type, severity)
                )
                alerts.append(alert)

        # Add memory leak alerts
        alerts.extend(self.memory_detector.detect_leaks())

        # Add thread deadlock alerts
        alerts.extend(self.thread_monitor.detect_dead_threads())

        return alerts

    def _get_recommendations(self, resource_type: ResourceType, severity: AlertSeverity) -> List[str]:
        """Get recommendations based on resource type and severity."""
        recommendations = []

        if resource_type == ResourceType.MEMORY:
            recommendations = [
                "Check for memory leaks using memory profiling",
                "Review object creation patterns",
                "Consider implementing object pooling",
                "Monitor garbage collection frequency"
            ]
            if severity == AlertSeverity.EMERGENCY:
                recommendations.insert(0, "Immediate action required: restart service")

        elif resource_type == ResourceType.CPU:
            recommendations = [
                "Profile CPU usage to identify bottlenecks",
                "Check for infinite loops or heavy computations",
                "Consider optimizing algorithms",
                "Review thread usage and synchronization"
            ]

        elif resource_type == ResourceType.THREADS:
            recommendations = [
                "Review thread creation patterns",
                "Check for thread leaks",
                "Consider using thread pools",
                "Monitor thread lifecycle"
            ]

        elif resource_type == ResourceType.FILE_DESCRIPTORS:
            recommendations = [
                "Check for file handle leaks",
                "Ensure files are properly closed",
                "Review network connection handling",
                "Monitor file operations"
            ]

        return recommendations

    def get_resource_summary(self) -> Dict[str, Any]:
        """Get summary of all resource usage."""
        summary = {}

        for resource_type in ResourceType:
            trend = self.resource_trends[resource_type]
            threshold = self.resource_thresholds.get(resource_type)

            summary[resource_type.value] = {
                "current_value": trend.measurements[-1].value if trend.measurements else 0,
                "average": trend.get_average(),
                "trend": trend.get_trend_description(),
                "unit": threshold.measurement_unit if threshold else "",
                "thresholds": {
                    "warning": threshold.warning_threshold if threshold else None,
                    "critical": threshold.critical_threshold if threshold else None,
                    "emergency": threshold.emergency_threshold if threshold else None
                } if threshold else None
            }

        # Add memory leak information
        summary["memory_leak_detection"] = {
            "snapshots_taken": len(self.memory_detector.snapshots),
            "tracemalloc_enabled": self.memory_detector.tracemalloc_enabled,
            "top_consumers": self.memory_detector.get_top_memory_consumers(5)
        }

        # Add thread information
        summary["threads"] = self.thread_monitor.get_thread_summary()

        return summary

    async def start_monitoring(self) -> None:
        """Start background monitoring."""
        if self.monitoring_task is None:
            self.monitoring_task = asyncio.create_task(self._monitoring_loop())
            logger.info("Process monitoring started")

    async def stop_monitoring(self) -> None:
        """Stop background monitoring."""
        if self.monitoring_task:
            self._shutdown_event.set()
            try:
                await asyncio.wait_for(self.monitoring_task, timeout=5.0)
            except asyncio.TimeoutError:
                self.monitoring_task.cancel()
            logger.info("Process monitoring stopped")

    async def _monitoring_loop(self) -> None:
        """Background monitoring loop."""
        while not self._shutdown_event.is_set():
            try:
                # Take memory snapshot
                self.memory_detector.take_snapshot()

                # Update thread states
                self.thread_monitor.update_thread_states()

                # Check thresholds and generate alerts
                alerts = self.check_thresholds()

                # Trigger alerts
                for alert in alerts:
                    for callback in self.alert_callbacks:
                        try:
                            await callback(alert)
                        except Exception as e:
                            logger.error(f"Alert callback failed: {e}")

                await asyncio.sleep(self.measurement_interval)

            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"Error in monitoring loop: {e}")
                await asyncio.sleep(self.measurement_interval)

    def force_garbage_collection(self) -> Dict[str, Any]:
        """Force garbage collection and return statistics."""
        initial_objects = len(gc.get_objects())

        # Run garbage collection
        collected = gc.collect()

        final_objects = len(gc.get_objects())

        return {
            "objects_before": initial_objects,
            "objects_after": final_objects,
            "objects_collected": collected,
            "gc_stats": gc.get_stats()
        }


# Global instance
_process_monitor_service: Optional[ProcessMonitorService] = None


def get_process_monitor_service() -> ProcessMonitorService:
    """Get the global process monitor service instance."""
    global _process_monitor_service
    if _process_monitor_service is None:
        _process_monitor_service = ProcessMonitorService()
    return _process_monitor_service


# Convenience functions
async def start_process_monitoring() -> None:
    """Start process monitoring."""
    service = get_process_monitor_service()
    await service.start_monitoring()


def get_resource_summary() -> Dict[str, Any]:
    """Get resource usage summary."""
    service = get_process_monitor_service()
    return service.get_resource_summary()


def force_garbage_collection() -> Dict[str, Any]:
    """Force garbage collection."""
    service = get_process_monitor_service()
    return service.force_garbage_collection()
