#!/usr/bin/env python3
"""
Generate comprehensive development history using RAG.

Uses the RAG endpoint to create an intelligent summary of the last 100 commits.
"""

import httpx
import time
from datetime import datetime
from pathlib import Path

client = httpx.Client(timeout=300.0)  # 5 minutes for comprehensive generation
base_url = "http://localhost:8000"

print("=" * 80)
print("🔍 GENERATING DEVELOPMENT HISTORY VIA RAG")
print("=" * 80)

# Test 1: Simple RAG test
print("\n1. Testing RAG endpoint...")
try:
    response = client.post(
        f"{base_url}/api/v1/ask",
        json={
            "question": "What is the ecosystem-mcp service?",
            "n_results": 5,
            "temperature": 0.7
        }
    )
    
    if response.status_code == 200:
        result = response.json()
        print("✅ RAG is working!")
        print(f"   Answer length: {len(result['answer'])} characters")
        print(f"   Sources: {len(result['sources'])}")
        print(f"   Confidence: {result['confidence']:.1%}")
    else:
        print(f"❌ RAG test failed: {response.status_code}")
        print(f"   Error: {response.text[:300]}")
        exit(1)
except Exception as e:
    print(f"❌ Error: {e}")
    exit(1)

# Test 2: Generate comprehensive development history
print("\n" + "=" * 80)
print("2. Generating comprehensive development history...")
print("=" * 80)

query = """Create a comprehensive development history document for the ecosystem-mcp service 
based on the last 100 commits. Include:

1. Major milestones and features added
2. Key architectural decisions
3. Critical bug fixes and their impact
4. Testing and validation improvements
5. Infrastructure and deployment changes
6. Performance optimizations
7. Integration with other services

Organize chronologically and highlight the most significant developments. 
Include specific commit details, dates, and the evolution of the codebase."""

print(f"\nQuery: {query[:150]}...")
print("\n⏳ Generating intelligent summary (this may take 30-60 seconds)...")
print("   (Using LLM to synthesize information from indexed commits)\n")

start_time = time.time()

try:
    response = client.post(
        f"{base_url}/api/v1/ask",
        json={
            "question": query,
            "n_results": 25,  # Get more context for comprehensive history
            "prefer_recent": True,
            "temperature": 0.5  # Balanced between creativity and accuracy
        }
    )
    
    generation_time = time.time() - start_time
    
    if response.status_code == 200:
        result = response.json()
        
        print(f"✅ History generated in {generation_time:.1f} seconds!")
        print(f"\n📊 Generation Stats:")
        print(f"   Answer length: {len(result['answer']):,} characters")
        print(f"   Sources used: {len(result['sources'])}")
        print(f"   Confidence: {result['confidence']:.1%}")
        print(f"   Temperature: {result['metadata']['temperature']}")
        print(f"   Documents analyzed: {result['metadata']['documents_used']}")
        
        # Show top sources
        print(f"\n📚 Top Sources:")
        for i, source in enumerate(result['sources'][:5], 1):
            print(f"   {i}. {source['file_path'][:65]}")
            print(f"      Score: {source['relevance_score']:.3f} → {source['adjusted_score']:.3f}")
            if source.get('recency_days') is not None:
                print(f"      Age: {source['recency_days']} days")
        
        # Create document
        document = f"""# Ecosystem-MCP Development History

**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Method**: RAG (Retrieval Augmented Generation)  
**Sources**: {len(result['sources'])} documents analyzed  
**Confidence**: {result['confidence']:.1%}  
**Generation Time**: {generation_time:.1f} seconds

---

## 📜 INTELLIGENT SUMMARY

{result['answer']}

---

## 📚 SOURCES & CITATIONS

This history was generated by analyzing {len(result['sources'])} source documents using semantic search 
and LLM-based synthesis. Sources are ranked by relevance and recency.

### Primary Sources

"""
        
        # Add detailed sources
        for i, source in enumerate(result['sources'], 1):
            document += f"{i}. **{source['file_path']}**\n"
            document += f"   - Relevance: {source['relevance_score']:.3f} (adjusted: {source['adjusted_score']:.3f})\n"
            if source.get('recency_days') is not None:
                document += f"   - Age: {source['recency_days']} days old\n"
            if source.get('updated_at'):
                document += f"   - Updated: {source['updated_at'][:10]}\n"
            document += "\n"
        
        document += f"""
---

## 🔧 GENERATION METADATA

- **RAG Model**: LLaMA 3.1 8B (Quantized Q8_0)
- **Embedding Model**: nomic-embed-text
- **Vector Database**: ChromaDB
- **Documents Indexed**: {result['metadata']['documents_used']}
- **Query Type**: Comprehensive historical analysis
- **Temperature**: {result['metadata']['temperature']} (balanced)
- **Prefer Recent**: {result['metadata']['prefer_recent']}
- **Top Document Score**: {result['metadata']['top_score']:.3f}

---

## 🎯 SCORING METHODOLOGY

Documents were scored using a multi-factor algorithm:

1. **Semantic Similarity** (Base): Vector similarity between query and document
2. **Recency Boost** (0-15%): Recent documents receive higher scores
   - 0-7 days: +15%
   - 8-30 days: +10%
   - 31-90 days: +5%
3. **Version Matching** (10%): Documents matching version numbers in query
4. **Duplicate Removal**: Identical content is deduplicated

**Final Confidence**: {result['confidence']:.1%}
- 50% based on top document relevance
- 30% based on supporting document count
- 20% based on answer completeness

---

*This document was automatically generated using RAG (Retrieval Augmented Generation).  
The ecosystem-mcp service retrieved relevant documents and used an LLM to synthesize  
a coherent, intelligent summary rather than simply concatenating search results.*

**Generation Timestamp**: {datetime.now().isoformat()}
"""
        
        # Save document
        output_path = "DEVELOPMENT_HISTORY_RAG.md"
        Path(output_path).write_text(document)
        
        print(f"\n💾 Document saved: {output_path}")
        print(f"   Size: {len(document):,} characters")
        print(f"   Generated using RAG with {len(result['sources'])} sources")
        
        # Show preview
        print(f"\n📝 PREVIEW (first 500 characters):")
        print("-" * 80)
        print(result['answer'][:500] + "...")
        print("-" * 80)
        
        print("\n" + "=" * 80)
        print("✅ DEVELOPMENT HISTORY GENERATION COMPLETE!")
        print("=" * 80)
        print(f"\nFile: {output_path}")
        print(f"Method: RAG (Intelligent Synthesis)")
        print(f"Quality: Coherent narrative from {len(result['sources'])} sources")
        
    else:
        print(f"❌ Failed: {response.status_code}")
        print(f"Error: {response.text[:500]}")
        exit(1)
        
except Exception as e:
    print(f"❌ Error: {e}")
    import traceback
    traceback.print_exc()
    exit(1)

