#!/usr/bin/env python3
"""Query ecosystem-mcp and save results."""

import httpx
import sys
from datetime import datetime
from pathlib import Path

client = httpx.Client(timeout=120.0)
base_url = "http://localhost:8000"

print("=" * 80)
print("🔍 QUERYING ECOSYSTEM-MCP")
print("=" * 80)

# Get current stats
stats = client.get(f"{base_url}/api/v1/admin/stats").json()
doc_count = stats['documents']['total']
embedding_count = stats['documents']['embeddings']

print(f"\n📊 Current Stats:")
print(f"  Documents: {doc_count:,}")
print(f"  Embeddings: {embedding_count:,}")

# Query 1: Ecosystem Description
print("\n" + "-" * 80)
print("Query 1: What is ecosystem-mcp?")
print("-" * 80)

query1 = """What is the ecosystem-mcp service? Describe its purpose, architecture, 
key features, capabilities, and how it fits into the larger microservices ecosystem. 
Include information about its data storage, processing pipeline, and API endpoints."""

response1 = client.post(
    f"{base_url}/api/v1/search",
    json={"query": query1, "limit": 15}
)

if response1.status_code != 200:
    print(f"❌ Query failed: {response1.status_code}")
    sys.exit(1)

results1 = response1.json().get('results', [])
print(f"✅ Retrieved {len(results1)} results")

# Show top 5
print("\nTop 5 results:")
for i, r in enumerate(results1[:5], 1):
    print(f"  {i}. {r['file_path'][:65]:<65} (score: {r['score']:.3f})")

# Query 2: Development History
print("\n" + "-" * 80)
print("Query 2: Development History")
print("-" * 80)

query2 = """Describe the development history of the ecosystem-mcp service. 
What were the major milestones, features added over time, bugs fixed, architectural 
decisions, and key improvements? Include testing, validation, and refactoring efforts."""

response2 = client.post(
    f"{base_url}/api/v1/search",
    json={"query": query2, "limit": 15}
)

if response2.status_code != 200:
    print(f"❌ Query failed: {response2.status_code}")
    sys.exit(1)

results2 = response2.json().get('results', [])
print(f"✅ Retrieved {len(results2)} results")

# Show top 5
print("\nTop 5 results:")
for i, r in enumerate(results2[:5], 1):
    print(f"  {i}. {r['file_path'][:65]:<65} (score: {r['score']:.3f})")

# Compile document
print("\n" + "=" * 80)
print("💾 COMPILING DOCUMENT")
print("=" * 80)

# Build description section
description_parts = []
for r in results1:
    if r['score'] > 0.5:  # Only include highly relevant results
        snippet = r.get('snippet', r.get('content', ''))
        description_parts.append(f"### {r['file_path']}\n\n{snippet}\n")

description = "\n---\n\n".join(description_parts) if description_parts else "No highly relevant results found."

# Build history section
history_parts = []
for r in results2:
    if r['score'] > 0.5:  # Only include highly relevant results
        snippet = r.get('snippet', r.get('content', ''))
        history_parts.append(f"### {r['file_path']}\n\n{snippet}\n")

history = "\n---\n\n".join(history_parts) if history_parts else "No highly relevant results found."

# Calculate metadata
top_score1 = f"{results1[0]['score']:.3f}" if results1 else "N/A"
top_source1 = results1[0]['file_path'] if results1 else "N/A"
top_score2 = f"{results2[0]['score']:.3f}" if results2 else "N/A"
top_source2 = results2[0]['file_path'] if results2 else "N/A"

# Create document
document = f"""# Ecosystem-MCP: Service Description & Development History

**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Source**: Ecosystem-MCP Semantic Search  
**Documents Indexed**: {doc_count:,}  
**Embeddings Generated**: {embedding_count:,}

---

## 🏗️ SERVICE DESCRIPTION

The following information was compiled from {len([r for r in results1 if r['score'] > 0.5])} highly relevant documents (similarity > 0.5):

{description}

---

## 📜 DEVELOPMENT HISTORY

The following information was compiled from {len([r for r in results2 if r['score'] > 0.5])} highly relevant documents (similarity > 0.5):

{history}

---

## 📊 QUERY METADATA

### Query 1: Service Description
- **Results**: {len(results1)} total
- **High relevance (>0.5)**: {len([r for r in results1 if r['score'] > 0.5])}
- **Top score**: {top_score1}
- **Top source**: {top_source1}

### Query 2: Development History
- **Results**: {len(results2)} total
- **High relevance (>0.5)**: {len([r for r in results2 if r['score'] > 0.5])}
- **Top score**: {top_score2}
- **Top source**: {top_source2}

---

## 🔧 TECHNICAL DETAILS

- **Query Date**: {datetime.now().isoformat()}
- **Total Documents**: {doc_count:,}
- **Total Embeddings**: {embedding_count:,}
- **Search Engine**: ChromaDB + Ollama embeddings
- **Model**: nomic-embed-text (via Ollama)
- **Database**: PostgreSQL + ChromaDB
- **Processing**: Redis Streams + Background Workers

---

*This document was automatically generated by querying the Ecosystem-MCP 
semantic search service. The content is derived from indexed documentation, 
code files, and commit messages from the repository.*
"""

# Save document
output_path = "ECOSYSTEM_MCP_DESCRIPTION_AND_HISTORY.md"
Path(output_path).write_text(document)

print(f"\n✅ Document saved: {output_path}")
print(f"   Size: {len(document):,} characters")
print(f"   High-relevance sources: {len([r for r in results1 + results2 if r['score'] > 0.5])}")

print("\n" + "=" * 80)
print("✅ COMPLETE!")
print("=" * 80)

