#!/usr/bin/env python3
"""Query ecosystem-mcp for all services summary."""

import httpx
from pathlib import Path
from datetime import datetime

client = httpx.Client(timeout=120.0)
base_url = "http://localhost:8000"

print("=" * 80)
print("🔍 QUERYING: ALL SERVICES IN ECOSYSTEM")
print("=" * 80)

# Query for all services
query = """List and describe all the microservices in the ecosystem. For each service, 
include its name, purpose, key capabilities, API endpoints, dependencies, and role in 
the overall architecture. Include both core services and supporting services."""

print(f"\nExecuting query...")
response = client.post(
    f"{base_url}/api/v1/search",
    json={"query": query, "limit": 25}  # Get more results for comprehensive coverage
)

if response.status_code != 200:
    print(f"❌ Query failed: {response.status_code}")
    exit(1)

results = response.json().get('results', [])
print(f"✅ Retrieved {len(results)} results\n")

# Show top 10
print("Top 10 most relevant sources:")
for i, r in enumerate(results[:10], 1):
    print(f"  {i:2d}. {r['file_path'][:60]:<60} (score: {r['score']:.3f})")

# Compile comprehensive service summary
print("\n" + "=" * 80)
print("📝 COMPILING SERVICE SUMMARY")
print("=" * 80)

service_content = []
for r in results:
    if r['score'] > 0.5:  # Only high-relevance results
        snippet = r.get('snippet', '')
        service_content.append(f"### Source: {r['file_path']} (relevance: {r['score']:.3f})\n\n{snippet}\n")

# Get stats
stats = client.get(f"{base_url}/api/v1/admin/stats").json()

# Calculate metadata
top_score = f"{results[0]['score']:.3f}" if results else "N/A"
top_source = results[0]['file_path'] if results else "N/A"
high_rel_count = len([r for r in results if r['score'] > 0.5])

# Create document
document = f"""# Ecosystem Services Summary

**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Source**: Ecosystem-MCP Semantic Search  
**Documents Indexed**: {stats['documents']['total']:,}  
**Query Results**: {len(results)} total, {high_rel_count} high-relevance

---

## 🎯 QUERY

{query}

---

## 📊 ALL SERVICES IN THE ECOSYSTEM

The following information was compiled from {high_rel_count} highly relevant documents:

{chr(10).join(service_content)}

---

## 📈 QUERY METADATA

- **Total Results**: {len(results)}
- **High Relevance (>0.5)**: {high_rel_count}
- **Top Score**: {top_score}
- **Top Source**: {top_source}
- **Query Date**: {datetime.now().isoformat()}

---

*Generated by querying the Ecosystem-MCP semantic search service.*
"""

# Save document
output_path = "ECOSYSTEM_SERVICES_SUMMARY.md"
Path(output_path).write_text(document)

print(f"\n✅ Document saved: {output_path}")
print(f"   Size: {len(document):,} characters")
print(f"   High-relevance sources: {high_rel_count}")
print("\n" + "=" * 80)

