"""
Code Templates

Templates for generating client SDKs in various programming languages
and frameworks from OpenAPI specifications.
"""

import json
from typing import Dict, List, Any, Optional
from textwrap import dedent


class CodeTemplates:
    """
    Code generation templates for multiple programming languages.

    Provides templates for:
    - REST API clients
    - Async clients
    - Model classes
    - Test files
    - Documentation
    - Configuration files
    """

    @staticmethod
    def get_python_init_template(config) -> str:
        """Generate Python __init__.py file."""
        return f'''"""
{config.package_name}

{config.description}

Generated by LLM Documentation Ecosystem API Dashboard.
"""

from .{config.package_name.replace("-", "_")} import *
from .models import *

__version__ = "{config.version}"
__author__ = "{config.author}"
'''

    @staticmethod
    def get_python_client_template(spec: Dict[str, Any], config) -> str:
        """Generate Python REST API client."""
        paths = spec.get("paths", {})
        endpoints = []

        for path, methods in paths.items():
            for method, operation in methods.items():
                if isinstance(operation, dict):
                    operation_id = operation.get("operationId", f"{method}_{path.replace('/', '_').strip('_')}")
                    summary = operation.get("summary", "")
                    endpoints.append((operation_id, method.upper(), path, summary))

        endpoint_methods = []
        for operation_id, method, path, summary in endpoints:
            params = []
            query_params = []
            path_params = []

            if "parameters" in spec["paths"][path][method.lower()]:
                for param in spec["paths"][path][method.lower()]["parameters"]:
                    param_name = param["name"]
                    param_in = param.get("in", "query")
                    param_required = param.get("required", False)

                    if param_in == "path":
                        path_params.append(param_name)
                    elif param_in == "query":
                        query_params.append(param_name)

                    params.append(f"{param_name}: {'Optional[' if not param_required else ''}{CodeTemplates._python_type_from_schema(param.get('schema', {}))}{'Optional]' if not param_required else ''} = None")

            # Handle request body
            has_body = method in ["POST", "PUT", "PATCH"] and "requestBody" in spec["paths"][path][method.lower()]
            if has_body:
                params.append("data: Optional[Dict[str, Any]] = None")

            params_str = ", ".join(params) if params else ""
            path_formatted = path.replace("{", "{").replace("}", "}")

            method_template = f'''
    def {operation_id}(self, {params_str}) -> Dict[str, Any]:
        """{summary}"""
        path = f"{path_formatted}"'''
            if path_params:
                method_template += f'''
        path = path.format({", ".join(f"{p}={p}" for p in path_params)})'''

            method_template += f'''
        params = {{}}'''
            if query_params:
                for qp in query_params:
                    method_template += f'''
        if {qp} is not None:
            params["{qp}"] = {qp}'''

            method_template += f'''
        response = self.session.request("{method}", f"{{self.base_url}}{{path}}", params=params'''

            if has_body:
                method_template += ", json=data"

            method_template += ''')
        response.raise_for_status()
        return response.json()'''

            endpoint_methods.append(method_template)

        return f'''"""
{config.package_name} API Client

{config.description}

Generated by LLM Documentation Ecosystem API Dashboard.
"""

import requests
from typing import Dict, Any, Optional
from .models import *


class {config.package_name.replace("-", "").title()}Client:
    """
    REST API client for {config.package_name}.

    Generated from OpenAPI specification.
    """

    def __init__(self, base_url: str, api_key: Optional[str] = None):
        """
        Initialize the API client.

        Args:
            base_url: Base URL for the API
            api_key: Optional API key for authentication
        """
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()

        if api_key:
            self.session.headers.update({{"Authorization": f"Bearer {{api_key}}"}})

        self.session.headers.update({{
            "User-Agent": "{config.package_name}/{config.version}",
            "Content-Type": "application/json",
            "Accept": "application/json"
        }})

{chr(10).join(endpoint_methods)}

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.session.close()
'''

    @staticmethod
    def get_python_async_client_template(spec: Dict[str, Any], config) -> str:
        """Generate Python async REST API client."""
        paths = spec.get("paths", {})
        endpoints = []

        for path, methods in paths.items():
            for method, operation in methods.items():
                if isinstance(operation, dict):
                    operation_id = f"{operation.get('operationId', f'{method}_{path.replace('/', '_').strip('_')}')}_async"
                    summary = operation.get("summary", "")
                    endpoints.append((operation_id, method.upper(), path, summary))

        endpoint_methods = []
        for operation_id, method, path, summary in endpoints:
            method_template = f'''
    async def {operation_id}(self) -> Dict[str, Any]:
        """{summary} (async)"""
        async with self.session.get(f"{{self.base_url}}{path}") as response:
            response.raise_for_status()
            return await response.json()'''

            endpoint_methods.append(method_template)

        return f'''"""
{config.package_name} Async API Client

{config.description}

Generated by LLM Documentation Ecosystem API Dashboard.
"""

import aiohttp
from typing import Dict, Any, Optional
from .models import *


class {config.package_name.replace("-", "").title()}AsyncClient:
    """
    Async REST API client for {config.package_name}.

    Generated from OpenAPI specification.
    """

    def __init__(self, base_url: str, api_key: Optional[str] = None):
        """
        Initialize the async API client.

        Args:
            base_url: Base URL for the API
            api_key: Optional API key for authentication
        """
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key

    async def __aenter__(self):
        self.session = aiohttp.ClientSession(headers={{
            "User-Agent": "{config.package_name}/{config.version}",
            "Content-Type": "application/json",
            "Accept": "application/json"
        }})

        if self.api_key:
            self.session.headers.update({{"Authorization": f"Bearer {{self.api_key}}"}})

        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        await self.session.close()

{chr(10).join(endpoint_methods)}
'''

    @staticmethod
    def get_python_models_template(schemas: Dict[str, Any], config) -> str:
        """Generate Python Pydantic models."""
        model_classes = []

        for schema_name, schema in schemas.items():
            if isinstance(schema, dict) and schema.get("type") == "object":
                properties = schema.get("properties", {})
                required = schema.get("required", [])

                fields = []
                for prop_name, prop_schema in properties.items():
                    field_type = CodeTemplates._python_type_from_schema(prop_schema)
                    default_value = "..."
                    if prop_name not in required:
                        field_type = f"Optional[{field_type}]"
                        default_value = "None"

                    fields.append(f"    {prop_name}: {field_type} = {default_value}")

                model_class = f'''
class {schema_name}(BaseModel):
    """Model for {schema_name}"""
{chr(10).join(fields)}
'''
                model_classes.append(model_class)

        return f'''"""
API Models

Generated Pydantic models for {config.package_name}.

Generated by LLM Documentation Ecosystem API Dashboard.
"""

from pydantic import BaseModel
from typing import Optional, List, Dict, Any

{chr(10).join(model_classes)}
'''

    @staticmethod
    def get_python_test_template(spec: Dict[str, Any], config) -> str:
        """Generate Python unit tests."""
        test_methods = []

        paths = spec.get("paths", {})
        for path, methods in paths.items():
            for method, operation in methods.items():
                if isinstance(operation, dict):
                    operation_id = operation.get("operationId", f"{method}_{path.replace('/', '_').strip('_')}")
                    test_method = f'''
    def test_{operation_id}(self):
        """Test {operation_id}"""
        # TODO: Implement test
        with self.client as client:
            # result = client.{operation_id}()
            # self.assertIsInstance(result, dict)
            pass
'''
                    test_methods.append(test_method)

        return f'''"""
Unit Tests for {config.package_name}

Generated by LLM Documentation Ecosystem API Dashboard.
"""

import unittest
from {config.package_name.replace("-", "_")} import {config.package_name.replace("-", "").title()}Client


class Test{config.package_name.replace("-", "").title()}Client(unittest.TestCase):
    """Unit tests for the API client."""

    def setUp(self):
        """Set up test fixtures."""
        self.base_url = "http://localhost:8000"  # Change to your test server
        self.client = {config.package_name.replace("-", "").title()}Client(self.base_url)

{chr(10).join(test_methods)}

    def tearDown(self):
        """Clean up test fixtures."""
        pass


if __name__ == "__main__":
    unittest.main()
'''

    @staticmethod
    def get_python_setup_template(config, dependencies: List[str]) -> str:
        """Generate Python setup.py."""
        deps_str = "\n".join(f'        "{dep}",' for dep in dependencies)

        return f'''"""
Setup script for {config.package_name}

Generated by LLM Documentation Ecosystem API Dashboard.
"""

from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="{config.package_name}",
    version="{config.version}",
    author="{config.author}",
    description="{config.description}",
    long_description=long_description,
    long_description_content_type="text/markdown",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.8",
    install_requires=[
{deps_str}
    ],
)
'''

    @staticmethod
    def get_python_readme_template(spec: Dict[str, Any], config) -> str:
        """Generate Python README.md."""
        paths = spec.get("paths", {})
        endpoint_count = sum(len(methods) for methods in paths.values())

        return f'''# {config.package_name}

{config.description}

This package is automatically generated from the OpenAPI specification of the {config.package_name} service.

## Installation

```bash
pip install {config.package_name}
```

## Usage

```python
from {config.package_name.replace("-", "_")} import {config.package_name.replace("-", "").title()}Client

# Initialize client
client = {config.package_name.replace("-", "").title()}Client(
    base_url="https://api.example.com",
    api_key="your-api-key"  # Optional
)

# Make API calls
with client as c:
    result = c.some_endpoint()
    print(result)
```

## API Reference

This client provides access to {endpoint_count} API endpoints:

'''

    @staticmethod
    def get_python_examples_template(spec: Dict[str, Any], config) -> str:
        """Generate Python examples."""
        return f'''"""
Usage examples for {config.package_name}

Generated by LLM Documentation Ecosystem API Dashboard.
"""

from {config.package_name.replace("-", "_")} import {config.package_name.replace("-", "").title()}Client


def basic_usage():
    """Basic usage example."""
    client = {config.package_name.replace("-", "").title()}Client(
        base_url="https://api.example.com"
    )

    with client as c:
        # Example API call
        result = c.get_health()
        print(f"Health check: {{result}}")


def with_authentication():
    """Usage with API key authentication."""
    client = {config.package_name.replace("-", "").title()}Client(
        base_url="https://api.example.com",
        api_key="your-api-key-here"
    )

    with client as c:
        # Authenticated API calls
        result = c.get_user_profile()
        print(f"User profile: {{result}}")


if __name__ == "__main__":
    basic_usage()
    with_authentication()
'''

    @staticmethod
    def get_typescript_client_template(spec: Dict[str, Any], config) -> str:
        """Generate TypeScript REST API client."""
        paths = spec.get("paths", {})
        endpoints = []

        for path, methods in paths.items():
            for method, operation in methods.items():
                if isinstance(operation, dict):
                    operation_id = operation.get("operationId", f"{method}{path.replace('/', '').replace('{', '').replace('}', '')}")
                    summary = operation.get("summary", "")
                    endpoints.append((operation_id, method.upper(), path, summary))

        endpoint_methods = []
        for operation_id, method, path, summary in endpoints:
            method_template = f'''
    async {operation_id}(): Promise<any> {{
        // {summary}
        const response = await fetch(`{{this.baseUrl}}{path}`, {{
            method: '{method}',
            headers: this.headers
        }});
        return response.json();
    }}'''

            endpoint_methods.append(method_template)

        return f'''/**
 * {config.package_name} API Client
 *
 * {config.description}
 *
 * Generated by LLM Documentation Ecosystem API Dashboard.
 */

export interface ClientConfig {{
    baseUrl: string;
    apiKey?: string;
}}

export class {config.package_name.replace("-", "").title()}Client {{
    private baseUrl: string;
    private headers: Record<string, string>;

    constructor(config: ClientConfig) {{
        this.baseUrl = config.baseUrl.replace(/\\/$/, '');
        this.headers = {{
            'Content-Type': 'application/json',
            'User-Agent': '{config.package_name}/{config.version}'
        }};

        if (config.apiKey) {{
            this.headers['Authorization'] = `Bearer ${{config.apiKey}}`;
        }}
    }}

{chr(10).join(endpoint_methods)}
}}
'''

    @staticmethod
    def get_typescript_types_template(schemas: Dict[str, Any], config) -> str:
        """Generate TypeScript type definitions."""
        type_definitions = []

        for schema_name, schema in schemas.items():
            if isinstance(schema, dict) and schema.get("type") == "object":
                properties = schema.get("properties", {})
                required = schema.get("required", [])

                fields = []
                for prop_name, prop_schema in properties.items():
                    field_type = CodeTemplates._typescript_type_from_schema(prop_schema)
                    if prop_name not in required:
                        field_type = f"{field_type} | undefined"

                    fields.append(f"    {prop_name}: {field_type};")

                type_def = f'''
export interface {schema_name} {{
{chr(10).join(fields)}
}}'''
                type_definitions.append(type_def)

        return f'''/**
 * Type definitions for {config.package_name}
 *
 * Generated by LLM Documentation Ecosystem API Dashboard.
 */

{chr(10).join(type_definitions)}
'''

    @staticmethod
    def get_typescript_test_template(spec: Dict[str, Any], config) -> str:
        """Generate TypeScript tests."""
        return f'''/**
 * Tests for {config.package_name} API Client
 *
 * Generated by LLM Documentation Ecosystem API Dashboard.
 */

import {{ {config.package_name.replace("-", "").title()}Client }} from '../src/index';

describe('{config.package_name.replace("-", "").title()}Client', () => {{
    let client: {config.package_name.replace("-", "").title()}Client;

    beforeEach(() => {{
        client = new {config.package_name.replace("-", "").title()}Client({{
            baseUrl: 'http://localhost:8000' // Change to your test server
        }});
    }});

    it('should initialize correctly', () => {{
        expect(client).toBeDefined();
    }});

    // TODO: Add more tests
}});
'''

    @staticmethod
    def get_typescript_package_template(config, dependencies: List[str]) -> str:
        """Generate TypeScript package.json."""
        deps_obj = {dep.split("@")[0]: dep.split("@")[1] if "@" in dep else "latest" for dep in dependencies}
        deps_str = json.dumps(deps_obj, indent=4)

        return f'''{{
    "name": "{config.package_name}",
    "version": "{config.version}",
    "description": "{config.description}",
    "main": "dist/index.js",
    "types": "dist/index.d.ts",
    "scripts": {{
        "build": "tsc",
        "test": "jest",
        "lint": "eslint src/**/*.ts",
        "format": "prettier --write src/**/*.ts"
    }},
    "author": "{config.author}",
    "license": "MIT",
    "dependencies": {deps_str},
    "devDependencies": {{
        "@types/jest": "^29.0.0",
        "@types/node": "^18.0.0",
        "jest": "^29.0.0",
        "typescript": "^4.8.0",
        "eslint": "^8.0.0",
        "prettier": "^2.8.0"
    }}
}}
'''

    @staticmethod
    def get_typescript_readme_template(spec: Dict[str, Any], config) -> str:
        """Generate TypeScript README.md."""
        return f'''# {config.package_name}

{config.description}

This package is automatically generated from the OpenAPI specification of the {config.package_name} service.

## Installation

```bash
npm install {config.package_name}
```

## Usage

```typescript
import {{ {config.package_name.replace("-", "").title()}Client }} from '{config.package_name}';

const client = new {config.package_name.replace("-", "").title()}Client({{
    baseUrl: 'https://api.example.com',
    apiKey: 'your-api-key' // Optional
}});

// Make API calls
const result = await client.someEndpoint();
console.log(result);
```

## API Reference

See the generated TypeScript definitions for complete API documentation.
'''

    @staticmethod
    def get_go_client_template(spec: Dict[str, Any], config) -> str:
        """Generate Go REST API client."""
        return f'''// Package {config.package_name.replace("-", "")} provides a client for the {config.package_name} API.
//
// {config.description}
//
// Generated by LLM Documentation Ecosystem API Dashboard.
package {config.package_name.replace("-", "")}

import (
    "bytes"
    "encoding/json"
    "fmt"
    "io"
    "net/http"
    "time"
)

// Client represents the API client
type Client struct {{
    BaseURL    string
    HTTPClient *http.Client
    APIKey     string
}}

// NewClient creates a new API client
func NewClient(baseURL, apiKey string) *Client {{
    return &Client{{
        BaseURL: baseURL,
        HTTPClient: &http.Client{{
            Timeout: 30 * time.Second,
        }},
        APIKey: apiKey,
    }}
}}

// makeRequest performs an HTTP request
func (c *Client) makeRequest(method, path string, body interface{{}}) (*http.Response, error) {{
    url := c.BaseURL + path

    var bodyReader io.Reader
    if body != nil {{
        jsonData, err := json.Marshal(body)
        if err != nil {{
            return nil, err
        }}
        bodyReader = bytes.NewBuffer(jsonData)
    }}

    req, err := http.NewRequest(method, url, bodyReader)
    if err != nil {{
        return nil, err
    }}

    req.Header.Set("Content-Type", "application/json")
    req.Header.Set("User-Agent", "{config.package_name}/{config.version}")
    if c.APIKey != "" {{
        req.Header.Set("Authorization", "Bearer "+c.APIKey)
    }}

    return c.HTTPClient.Do(req)
}}

// TODO: Add endpoint methods
'''

    @staticmethod
    def get_go_models_template(schemas: Dict[str, Any], config) -> str:
        """Generate Go model structs."""
        model_structs = []

        for schema_name, schema in schemas.items():
            if isinstance(schema, dict) and schema.get("type") == "object":
                properties = schema.get("properties", {})

                fields = []
                for prop_name, prop_schema in properties.items():
                    field_type = CodeTemplates._go_type_from_schema(prop_schema)
                    json_tag = f'`json:"{prop_name}"`'

                    # Convert to Go field name (PascalCase)
                    go_field_name = prop_name.replace("_", " ").title().replace(" ", "")

                    fields.append(f"    {go_field_name} {field_type} {json_tag}")

                struct_def = f'''
// {schema_name} represents the {schema_name} model
type {schema_name} struct {{
{chr(10).join(fields)}
}}'''
                model_structs.append(struct_def)

        return f'''// Package {config.package_name.replace("-", "")}models contains the API models
//
// Generated by LLM Documentation Ecosystem API Dashboard.
package {config.package_name.replace("-", "")}models

{chr(10).join(model_structs)}
'''

    @staticmethod
    def get_go_test_template(spec: Dict[str, Any], config) -> str:
        """Generate Go tests."""
        return f'''package {config.package_name.replace("-", "")}

import (
    "testing"
)

func TestClient(t *testing.T) {{
    client := NewClient("http://localhost:8000", "")

    if client == nil {{
        t.Fatal("Client should not be nil")
    }}

    // TODO: Add more tests
}}
'''

    @staticmethod
    def get_go_mod_template(config) -> str:
        """Generate Go go.mod file."""
        return f'''module {config.package_name}

go 1.19

require (
    // Add your dependencies here
)
'''

    @staticmethod
    def get_java_client_template(spec: Dict[str, Any], config) -> str:
        """Generate Java REST API client."""
        return f'''package {config.package_name.replace("-", "")};

/**
 * {config.package_name} API Client
 *
 * {config.description}
 *
 * Generated by LLM Documentation Ecosystem API Dashboard.
 */

import okhttp3.*;
import com.google.gson.Gson;
import java.io.IOException;
import java.util.concurrent.TimeUnit;

public class {config.package_name.replace("-", "").title()}Client {{
    private static final String USER_AGENT = "{config.package_name}/{config.version}";
    private static final MediaType JSON = MediaType.get("application/json; charset=utf-8");

    private final OkHttpClient httpClient;
    private final String baseUrl;
    private final Gson gson;

    public {config.package_name.replace("-", "").title()}Client(String baseUrl, String apiKey) {{
        this.baseUrl = baseUrl.replaceAll("/$", "");
        this.gson = new Gson();

        OkHttpClient.Builder builder = new OkHttpClient.Builder()
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .writeTimeout(30, TimeUnit.SECONDS);

        if (apiKey != null && !apiKey.isEmpty()) {{
            builder.addInterceptor(chain -> {{
                Request original = chain.request();
                Request.Builder requestBuilder = original.newBuilder()
                    .header("Authorization", "Bearer " + apiKey);
                Request request = requestBuilder.build();
                return chain.proceed(request);
            }});
        }}

        this.httpClient = builder.build();
    }}

    // TODO: Add endpoint methods

    private Request buildRequest(String method, String path) {{
        return new Request.Builder()
            .url(baseUrl + path)
            .addHeader("User-Agent", USER_AGENT)
            .method(method, null)
            .build();
    }}

    private Request buildRequest(String method, String path, String jsonBody) {{
        RequestBody body = RequestBody.create(jsonBody, JSON);
        return new Request.Builder()
            .url(baseUrl + path)
            .addHeader("User-Agent", USER_AGENT)
            .method(method, body)
            .build();
    }}
}}
'''

    @staticmethod
    def get_java_model_template(name: str, schema: Dict[str, Any], config) -> str:
        """Generate Java model class."""
        properties = schema.get("properties", {})

        fields = []
        getters_setters = []

        for prop_name, prop_schema in properties.items():
            field_type = CodeTemplates._java_type_from_schema(prop_schema)
            field_name = CodeTemplates._camel_case(prop_name)

            fields.append(f"    private {field_type} {field_name};")

            # Getter
            getter = f'''
    public {field_type} get{CodeTemplates._pascal_case(prop_name)}() {{
        return {field_name};
    }}'''
            getters_setters.append(getter)

            # Setter
            setter = f'''
    public void set{CodeTemplates._pascal_case(prop_name)}({field_type} {field_name}) {{
        this.{field_name} = {field_name};
    }}'''
            getters_setters.append(setter)

        return f'''package {config.package_name.replace("-", "")}.models;

/**
 * Model class for {name}
 *
 * Generated by LLM Documentation Ecosystem API Dashboard.
 */
public class {name} {{
{chr(10).join(fields)}

    public {name}() {{
    }}

{chr(10).join(getters_setters)}
}}
'''

    @staticmethod
    def get_java_test_template(spec: Dict[str, Any], config) -> str:
        """Generate Java tests."""
        return f'''package {config.package_name.replace("-", "")};

/**
 * Tests for {config.package_name} API Client
 *
 * Generated by LLM Documentation Ecosystem API Dashboard.
 */

import org.junit.Test;
import static org.junit.Assert.*;

public class {config.package_name.replace("-", "").title()}ClientTest {{

    @Test
    public void testClientInitialization() {{
        {config.package_name.replace("-", "").title()}Client client =
            new {config.package_name.replace("-", "").title()}Client("http://localhost:8000", null);

        assertNotNull("Client should not be null", client);

        // TODO: Add more tests
    }}
}}
'''

    @staticmethod
    def get_java_pom_template(config, dependencies: List[str]) -> str:
        """Generate Java pom.xml."""
        deps_xml = []
        for dep in dependencies:
            group_id, artifact_id, version = dep.split(":")
            deps_xml.append(f'''        <dependency>
            <groupId>{group_id}</groupId>
            <artifactId>{artifact_id}</artifactId>
            <version>{version}</version>
        </dependency>''')

        return f'''<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/POM/4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>{config.package_name}</groupId>
    <artifactId>{config.package_name}</artifactId>
    <version>{config.version}</version>
    <packaging>jar</packaging>

    <name>{config.package_name}</name>
    <description>{config.description}</description>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
{chr(10).join(deps_xml)}
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
'''

    @staticmethod
    def _python_type_from_schema(schema: Dict[str, Any]) -> str:
        """Convert JSON schema type to Python type."""
        schema_type = schema.get("type", "string")

        type_mapping = {
            "string": "str",
            "integer": "int",
            "number": "float",
            "boolean": "bool",
            "array": "List[Any]",
            "object": "Dict[str, Any]"
        }

        return type_mapping.get(schema_type, "Any")

    @staticmethod
    def _typescript_type_from_schema(schema: Dict[str, Any]) -> str:
        """Convert JSON schema type to TypeScript type."""
        schema_type = schema.get("type", "string")

        type_mapping = {
            "string": "string",
            "integer": "number",
            "number": "number",
            "boolean": "boolean",
            "array": "any[]",
            "object": "Record<string, any>"
        }

        return type_mapping.get(schema_type, "any")

    @staticmethod
    def _go_type_from_schema(schema: Dict[str, Any]) -> str:
        """Convert JSON schema type to Go type."""
        schema_type = schema.get("type", "string")

        type_mapping = {
            "string": "string",
            "integer": "int",
            "number": "float64",
            "boolean": "bool",
            "array": "[]interface{}",
            "object": "map[string]interface{}"
        }

        return type_mapping.get(schema_type, "interface{}")

    @staticmethod
    def _java_type_from_schema(schema: Dict[str, Any]) -> str:
        """Convert JSON schema type to Java type."""
        schema_type = schema.get("type", "string")

        type_mapping = {
            "string": "String",
            "integer": "Integer",
            "number": "Double",
            "boolean": "Boolean",
            "array": "List<Object>",
            "object": "Map<String, Object>"
        }

        return type_mapping.get(schema_type, "Object")

    @staticmethod
    def _camel_case(s: str) -> str:
        """Convert snake_case to camelCase."""
        parts = s.split("_")
        return parts[0] + "".join(word.capitalize() for word in parts[1:])

    @staticmethod
    def _pascal_case(s: str) -> str:
        """Convert snake_case to PascalCase."""
        return "".join(word.capitalize() for word in s.split("_"))
