"""Domain exceptions for Doc Store service."""

from .exceptions import (
    DocStoreException,
    DocumentException,
    DocumentNotFoundException,
    DocumentValidationException,
    DocumentSizeExceededException,
    DocumentContentTypeException,
    VersioningException,
    VersionNotFoundException,
    VersionConflictException,
    TaggingException,
    TagNotFoundException,
    InvalidTagException,
    RelationshipsException,
    RelationshipNotFoundException,
    CircularReferenceException,
    BulkOperationException,
    BulkOperationTimeoutException,
    AnalyticsException,
    InvalidAnalyticsQueryException,
    LifecycleException,
    InvalidLifecycleTransitionException,
    NotificationsException,
    NotificationDeliveryException,
)

__all__ = [
    "DocStoreException",
    "DocumentException",
    "DocumentNotFoundException",
    "DocumentValidationException",
    "DocumentSizeExceededException",
    "DocumentContentTypeException",
    "VersioningException",
    "VersionNotFoundException",
    "VersionConflictException",
    "TaggingException",
    "TagNotFoundException",
    "InvalidTagException",
    "RelationshipsException",
    "RelationshipNotFoundException",
    "CircularReferenceException",
    "BulkOperationException",
    "BulkOperationTimeoutException",
    "AnalyticsException",
    "InvalidAnalyticsQueryException",
    "LifecycleException",
    "InvalidLifecycleTransitionException",
    "NotificationsException",
    "NotificationDeliveryException",
]
