# Memory-agent-specific configuration
# Inherits from shared base_config.yaml

# Override server port for memory-agent
server:
  port: 5040

# Memory-agent specific settings
memory:
  max_items: ${MEMORY_MAX_ITEMS:-1000}
  ttl_seconds: ${MEMORY_TTL_SECONDS:-3600}
  environment: ${ENVIRONMENT:-development}
  redis_url: ${REDIS_URL:-redis://redis:6379}
