"""Domain exceptions for Analysis Service."""

from .domain_exceptions import (
    AnalysisAlreadyRunningException,
    AnalysisException,
    AnalysisExecutionException,
    AnalysisNotFoundException,
    AnalysisTimeoutException,
    AuthorizationException,
    BusinessRuleViolation,
    ConfigurationException,
    DocumentException,
    DocumentNotFoundException,
    DocumentSizeExceededException,
    DocumentValidationException,
    DomainException,
    ExternalServiceException,
    FindingAlreadyResolvedException,
    FindingException,
    FindingNotFoundException,
    RepositoryConnectionException,
    RepositoryException,
    RepositoryNotFoundException,
    RepositorySyncException,
    ResourceLimitExceededException,
    SemanticAnalysisException,
    SentimentAnalysisException,
    ValidationException,
)

__all__ = [
    "DomainException",
    "DocumentException",
    "DocumentNotFoundException",
    "DocumentValidationException",
    "DocumentSizeExceededException",
    "AnalysisException",
    "AnalysisNotFoundException",
    "AnalysisExecutionException",
    "AnalysisTimeoutException",
    "AnalysisAlreadyRunningException",
    "FindingException",
    "FindingNotFoundException",
    "FindingAlreadyResolvedException",
    "RepositoryException",
    "RepositoryNotFoundException",
    "RepositoryConnectionException",
    "RepositorySyncException",
    "ExternalServiceException",
    "SemanticAnalysisException",
    "SentimentAnalysisException",
    "ConfigurationException",
    "AuthorizationException",
    "ResourceLimitExceededException",
    "ValidationException",
    "BusinessRuleViolation",
]
