# Individual Docker Compose for Orchestrator Service
# This allows the orchestrator to run independently with its own Redis instance

version: "3.9"

services:
  orchestrator:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ../../:/app:ro
      - ./:/app/services/orchestrator:rw
    environment:
      - REDIS_HOST=redis
      - ENVIRONMENT=development
    command: bash -lc "pip install --no-cache-dir fastapi uvicorn httpx pydantic redis aioredis && python services/orchestrator/main.py"
    ports:
      - "5099:5099"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5099/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
