"""
Report Formatter - Phase 5
Formats reports into multiple output formats (Markdown, JSON, PDF, HTML).
"""

from typing import Dict, Any, List
from abc import ABC, abstractmethod
import json

from .report_generator import ComprehensiveReport, ReportSection, ReportFormat


class ReportFormatter(ABC):
    """Abstract base class for report formatters."""
    
    @abstractmethod
    def format(self, report: ComprehensiveReport) -> str:
        """Format report to string output."""
        pass
    
    @abstractmethod
    def get_file_extension(self) -> str:
        """Get file extension for this format."""
        pass


class MarkdownFormatter(ReportFormatter):
    """Format reports as Markdown."""
    
    def format(self, report: ComprehensiveReport) -> str:
        """Format report as Markdown."""
        output = []
        
        # Title page
        output.append(f"# {report.title}\n")
        output.append(f"**Report ID:** {report.report_id}")
        output.append(f"**Generated:** {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}")
        output.append(f"**Roadmap ID:** {report.roadmap_id}\n")
        
        if report.memory_context_id:
            output.append(f"**Memory Context:** {report.memory_context_id}\n")
        
        # Metadata
        output.append("---\n")
        output.append("## Report Metadata\n")
        output.append(f"- **Total Pages:** {report.total_pages}")
        output.append(f"- **Word Count:** {report.word_count:,}")
        output.append(f"- **Artifacts Linked:** {report.artifact_count}")
        output.append(f"- **Sections:** {len(report.sections)}\n")
        
        # Table of contents
        output.append("---\n")
        output.append("## Table of Contents\n")
        for section in report.sections:
            output.append(f"{section.number}. [{section.title}](#{section.title.lower().replace(' ', '-')})")
        output.append("\n---\n")
        
        # Sections
        for section in report.sections:
            output.append(section.content)
            output.append("\n---\n")
        
        # Footer
        output.append(f"\n*Report generated by Project Planning Service*")
        output.append(f"\n*{report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}*\n")
        
        return "\n".join(output)
    
    def get_file_extension(self) -> str:
        return ".md"


class JSONFormatter(ReportFormatter):
    """Format reports as JSON."""
    
    def format(self, report: ComprehensiveReport) -> str:
        """Format report as JSON."""
        return json.dumps(report.to_dict(), indent=2, default=str)
    
    def get_file_extension(self) -> str:
        return ".json"


class HTMLFormatter(ReportFormatter):
    """Format reports as HTML."""
    
    def format(self, report: ComprehensiveReport) -> str:
        """Format report as HTML."""
        output = []
        
        # HTML header
        output.append("<!DOCTYPE html>")
        output.append("<html lang='en'>")
        output.append("<head>")
        output.append("    <meta charset='UTF-8'>")
        output.append("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>")
        output.append(f"    <title>{report.title}</title>")
        output.append("    <style>")
        output.append(self._get_css())
        output.append("    </style>")
        output.append("</head>")
        output.append("<body>")
        
        # Title page
        output.append("    <div class='title-page'>")
        output.append(f"        <h1>{report.title}</h1>")
        output.append("        <div class='metadata'>")
        output.append(f"            <p><strong>Report ID:</strong> {report.report_id}</p>")
        output.append(f"            <p><strong>Generated:</strong> {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}</p>")
        output.append(f"            <p><strong>Roadmap ID:</strong> {report.roadmap_id}</p>")
        output.append("        </div>")
        output.append("    </div>")
        
        # Table of contents
        output.append("    <div class='toc'>")
        output.append("        <h2>Table of Contents</h2>")
        output.append("        <ul>")
        for section in report.sections:
            output.append(f"            <li><a href='#section-{section.number}'>{section.number}. {section.title}</a></li>")
        output.append("        </ul>")
        output.append("    </div>")
        
        # Sections
        for section in report.sections:
            output.append(f"    <div class='section' id='section-{section.number}'>")
            output.append(self._markdown_to_html(section.content))
            output.append("    </div>")
        
        # Footer
        output.append("    <div class='footer'>")
        output.append("        <p>Report generated by Project Planning Service</p>")
        output.append(f"        <p>{report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}</p>")
        output.append("    </div>")
        
        output.append("</body>")
        output.append("</html>")
        
        return "\n".join(output)
    
    def _get_css(self) -> str:
        """Get CSS styles for HTML report."""
        return """
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }
        .title-page {
            text-align: center;
            padding: 50px 0;
            border-bottom: 2px solid #007bff;
            margin-bottom: 40px;
        }
        .title-page h1 {
            color: #007bff;
            font-size: 2.5em;
            margin-bottom: 20px;
        }
        .metadata {
            text-align: left;
            display: inline-block;
            margin-top: 30px;
        }
        .toc {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 40px;
        }
        .toc h2 {
            color: #007bff;
            margin-top: 0;
        }
        .toc ul {
            list-style-type: none;
            padding-left: 0;
        }
        .toc li {
            padding: 5px 0;
        }
        .toc a {
            color: #007bff;
            text-decoration: none;
        }
        .toc a:hover {
            text-decoration: underline;
        }
        .section {
            margin-bottom: 50px;
            padding: 30px;
            background: white;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .section h1 {
            color: #007bff;
            border-bottom: 2px solid #007bff;
            padding-bottom: 10px;
        }
        .section h2 {
            color: #0056b3;
            margin-top: 30px;
        }
        .section h3 {
            color: #495057;
            margin-top: 20px;
        }
        .footer {
            text-align: center;
            padding: 20px;
            color: #6c757d;
            font-size: 0.9em;
            border-top: 1px solid #dee2e6;
            margin-top: 50px;
        }
        ul, ol {
            padding-left: 30px;
        }
        li {
            margin-bottom: 8px;
        }
        code {
            background: #f8f9fa;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }
        pre {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #dee2e6;
            padding: 12px;
            text-align: left;
        }
        th {
            background: #007bff;
            color: white;
        }
        """
    
    def _markdown_to_html(self, markdown: str) -> str:
        """Simple markdown to HTML conversion."""
        import re
        
        html = markdown
        
        # Headers
        html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)
        html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
        html = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
        
        # Bold
        html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)
        
        # Lists
        lines = html.split('\n')
        in_list = False
        result = []
        for line in lines:
            if line.strip().startswith('- '):
                if not in_list:
                    result.append('<ul>')
                    in_list = True
                result.append(f'<li>{line.strip()[2:]}</li>')
            else:
                if in_list:
                    result.append('</ul>')
                    in_list = False
                result.append(line)
        
        if in_list:
            result.append('</ul>')
        
        html = '\n'.join(result)
        
        # Paragraphs
        html = re.sub(r'\n\n', r'</p><p>', html)
        html = '<p>' + html + '</p>'
        
        return html
    
    def get_file_extension(self) -> str:
        return ".html"


class PDFFormatter(ReportFormatter):
    """Format reports as PDF (placeholder - requires external library)."""
    
    def format(self, report: ComprehensiveReport) -> str:
        """Format report as PDF."""
        # This is a placeholder - actual PDF generation would require reportlab or weasyprint
        return f"PDF generation requires external library. Use HTML formatter and convert to PDF.\n\nReport ID: {report.report_id}"
    
    def get_file_extension(self) -> str:
        return ".pdf"


class ReportFormatterFactory:
    """Factory for creating report formatters."""
    
    @staticmethod
    def create_formatter(format: ReportFormat) -> ReportFormatter:
        """Create formatter for specified format."""
        formatters = {
            ReportFormat.MARKDOWN: MarkdownFormatter(),
            ReportFormat.JSON: JSONFormatter(),
            ReportFormat.HTML: HTMLFormatter(),
            ReportFormat.PDF: PDFFormatter()
        }
        
        formatter = formatters.get(format)
        if not formatter:
            raise ValueError(f"Unsupported format: {format}")
        
        return formatter

