"""
API Reference Generator

Generates API reference documentation.
Pass 3 of multi-pass documentation generation.
"""

import logging
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


class APIReferenceGenerator:
    """
    Generates API reference documentation from analysis results.
    
    Creates documentation for:
    - API endpoints
    - Request/response schemas
    - Authentication methods
    - Error codes
    - Rate limiting
    - API versioning
    """
    
    def __init__(self, model_router=None):
        """
        Initialize API reference generator.
        
        Args:
            model_router: Optional ModelRouter for LLM access
        """
        self.model_router = model_router
        logger.info("APIReferenceGenerator initialized")
    
    async def generate(
        self,
        analysis_report,
        context: Dict,
        config: Dict
    ) -> List[Dict]:
        """
        Generate API reference documentation.
        
        Args:
            analysis_report: Analysis results from Phase 3
            context: Generation context (previous passes, etc.)
            config: Generation configuration
        
        Returns:
            List of documentation artifacts
        """
        logger.info("🔌 Generating API reference documentation...")
        
        artifacts = []
        
        # Check if system has APIs
        has_api = self._has_api_services(analysis_report)
        
        if not has_api:
            logger.info("   ℹ️ No API services detected, generating basic reference")
            artifacts.append(self._generate_no_api_doc())
            return artifacts
        
        # 1. API Overview
        overview = await self._generate_api_overview(analysis_report)
        artifacts.append(overview)
        
        # 2. Generate endpoint documentation per service
        if analysis_report.service_map and analysis_report.service_map.services:
            for service in analysis_report.service_map.services:
                if service.has_api and service.endpoints:
                    endpoint_doc = await self._generate_service_endpoints(
                        service,
                        analysis_report
                    )
                    artifacts.append(endpoint_doc)
        
        # 3. Authentication documentation
        auth_doc = await self._generate_authentication_doc(analysis_report)
        artifacts.append(auth_doc)
        
        # 4. Error handling documentation
        error_doc = await self._generate_error_handling_doc(analysis_report)
        artifacts.append(error_doc)
        
        # 5. API best practices
        practices_doc = await self._generate_best_practices(analysis_report)
        artifacts.append(practices_doc)
        
        logger.info(f"   ✅ Generated {len(artifacts)} API reference artifacts")
        
        return artifacts
    
    def _has_api_services(self, analysis_report) -> bool:
        """Check if system has API services."""
        if not analysis_report.service_map:
            return False
        
        return any(s.has_api for s in analysis_report.service_map.services)
    
    def _generate_no_api_doc(self) -> Dict:
        """Generate documentation when no APIs are detected."""
        content = """# API Reference

## Overview

This project does not expose external APIs. It may be:
- A library or SDK
- A command-line tool
- An internal service
- A data processing pipeline

For integration information, see the component documentation.

---
*Generated by Ecosystem MCP - API Reference Generator*
"""
        
        return {
            'type': 'api_reference',
            'title': 'API Reference',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    async def _generate_api_overview(self, analysis_report) -> Dict:
        """Generate API overview document."""
        
        # Count total endpoints
        total_endpoints = 0
        api_services = []
        
        if analysis_report.service_map:
            for service in analysis_report.service_map.services:
                if service.has_api:
                    api_services.append(service.name)
                    total_endpoints += len(service.endpoints) if service.endpoints else 0
        
        content = f"""# API Reference Overview

## Introduction

This document provides comprehensive API reference for all exposed endpoints.

## API Services

Total API Services: {len(api_services)}  
Total Endpoints: {total_endpoints}

### Available Services

{self._format_api_services(api_services)}

## Base URLs

{self._generate_base_urls(analysis_report)}

## API Architecture

{self._describe_api_architecture(analysis_report)}

## Common Patterns

### Request Format

All requests should include:
- `Content-Type: application/json` header
- Valid authentication token (if required)
- Request body in JSON format (for POST/PUT/PATCH)

### Response Format

All responses follow a consistent structure:

```json
{{
  "success": true,
  "data": {{...}},
  "message": "Optional message",
  "timestamp": "2025-10-21T00:00:00Z"
}}
```

### HTTP Methods

- **GET** - Retrieve resources
- **POST** - Create new resources
- **PUT** - Update existing resources (full replacement)
- **PATCH** - Partial update of resources
- **DELETE** - Remove resources

## Versioning

{self._describe_api_versioning(analysis_report)}

## Rate Limiting

{self._describe_rate_limiting(analysis_report)}

---
*Generated by Ecosystem MCP - API Reference Generator*
"""
        
        return {
            'type': 'api_reference',
            'title': 'API Reference Overview',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    async def _generate_service_endpoints(
        self,
        service,
        analysis_report
    ) -> Dict:
        """Generate endpoint documentation for a service."""
        
        logger.info(f"   📋 Documenting API: {service.name}")
        
        content = f"""# API Reference: {service.name}

## Service Information

**Service:** {service.name}  
**Base Path:** `{self._infer_base_path(service)}`  
**Total Endpoints:** {len(service.endpoints) if service.endpoints else 0}

## Endpoints

{self._format_endpoints_detailed(service)}

## Request Examples

{self._generate_request_examples(service)}

## Response Schemas

{self._generate_response_schemas(service)}

---
*Generated by Ecosystem MCP - API Reference Generator*
"""
        
        return {
            'type': 'api_reference',
            'title': f'API Reference: {service.name}',
            'component_name': service.name,
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    async def _generate_authentication_doc(self, analysis_report) -> Dict:
        """Generate authentication documentation."""
        
        auth_methods = self._detect_auth_methods(analysis_report)
        
        content = f"""# Authentication

## Overview

{self._describe_authentication_overview(auth_methods)}

## Authentication Methods

{self._format_auth_methods(auth_methods)}

## Getting Authentication Token

### Request

```http
POST /api/v1/auth/login
Content-Type: application/json

{{
  "username": "your-username",
  "password": "your-password"
}}
```

### Response

```json
{{
  "success": true,
  "data": {{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
    "expires_at": "2025-10-22T00:00:00Z"
  }}
}}
```

## Using Authentication

### Header-based (Recommended)

```http
GET /api/v1/resource
Authorization: Bearer YOUR_TOKEN_HERE
```

### Query Parameter (Not Recommended)

```http
GET /api/v1/resource?token=YOUR_TOKEN_HERE
```

## Token Management

- **Expiration:** Tokens expire after 24 hours
- **Refresh:** Use refresh token endpoint to obtain new token
- **Revocation:** Logout endpoint revokes tokens immediately

## Security Best Practices

- Always use HTTPS in production
- Never commit tokens to version control
- Rotate tokens regularly
- Use environment variables for token storage

---
*Generated by Ecosystem MCP - API Reference Generator*
"""
        
        return {
            'type': 'api_reference',
            'title': 'Authentication',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    async def _generate_error_handling_doc(self, analysis_report) -> Dict:
        """Generate error handling documentation."""
        
        content = """# Error Handling

## Error Response Format

All error responses follow a consistent structure:

```json
{
  "success": false,
  "error": {
    "code": "ERROR_CODE",
    "message": "Human-readable error message",
    "details": {...}
  },
  "timestamp": "2025-10-21T00:00:00Z"
}
```

## HTTP Status Codes

### 2xx Success

| Code | Meaning | Description |
|------|---------|-------------|
| 200 | OK | Request succeeded |
| 201 | Created | Resource created successfully |
| 204 | No Content | Request succeeded, no content to return |

### 4xx Client Errors

| Code | Meaning | Description |
|------|---------|-------------|
| 400 | Bad Request | Invalid request format or parameters |
| 401 | Unauthorized | Authentication required or failed |
| 403 | Forbidden | Authenticated but not authorized |
| 404 | Not Found | Resource does not exist |
| 409 | Conflict | Resource conflict (e.g., duplicate) |
| 422 | Unprocessable Entity | Validation failed |
| 429 | Too Many Requests | Rate limit exceeded |

### 5xx Server Errors

| Code | Meaning | Description |
|------|---------|-------------|
| 500 | Internal Server Error | Unexpected server error |
| 502 | Bad Gateway | Upstream service error |
| 503 | Service Unavailable | Service temporarily unavailable |
| 504 | Gateway Timeout | Upstream service timeout |

## Common Error Codes

### Authentication Errors

- `AUTH_REQUIRED` - Authentication token required
- `AUTH_INVALID` - Invalid authentication token
- `AUTH_EXPIRED` - Authentication token expired

### Validation Errors

- `VALIDATION_FAILED` - Request validation failed
- `INVALID_PARAMETER` - Invalid parameter value
- `MISSING_PARAMETER` - Required parameter missing

### Resource Errors

- `RESOURCE_NOT_FOUND` - Resource does not exist
- `RESOURCE_CONFLICT` - Resource already exists
- `RESOURCE_LOCKED` - Resource is locked

### Rate Limiting

- `RATE_LIMIT_EXCEEDED` - Too many requests

## Error Handling Examples

### 400 Bad Request

```json
{
  "success": false,
  "error": {
    "code": "VALIDATION_FAILED",
    "message": "Request validation failed",
    "details": {
      "field": "email",
      "issue": "Invalid email format"
    }
  }
}
```

### 401 Unauthorized

```json
{
  "success": false,
  "error": {
    "code": "AUTH_REQUIRED",
    "message": "Authentication required"
  }
}
```

### 429 Rate Limit

```json
{
  "success": false,
  "error": {
    "code": "RATE_LIMIT_EXCEEDED",
    "message": "Rate limit exceeded",
    "details": {
      "limit": 100,
      "reset_at": "2025-10-21T01:00:00Z"
    }
  }
}
```

## Retry Logic

For 5xx errors and rate limiting:

1. Implement exponential backoff
2. Maximum 3 retry attempts
3. Respect `Retry-After` header

```python
import time

def api_call_with_retry(endpoint, max_retries=3):
    for attempt in range(max_retries):
        response = make_request(endpoint)
        
        if response.status_code < 500:
            return response
        
        # Exponential backoff
        time.sleep(2 ** attempt)
    
    raise Exception("Max retries exceeded")
```

---
*Generated by Ecosystem MCP - API Reference Generator*
"""
        
        return {
            'type': 'api_reference',
            'title': 'Error Handling',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    async def _generate_best_practices(self, analysis_report) -> Dict:
        """Generate API best practices documentation."""
        
        content = """# API Best Practices

## Request Best Practices

### 1. Use Appropriate HTTP Methods

- **GET** - Safe and idempotent, no side effects
- **POST** - Create new resources
- **PUT** - Full replacement of existing resource
- **PATCH** - Partial update of resource
- **DELETE** - Remove resource

### 2. Include Proper Headers

```http
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token>
X-Request-ID: <unique-id>
```

### 3. Pagination for Large Datasets

```http
GET /api/v1/resources?page=1&limit=50
```

### 4. Filtering and Sorting

```http
GET /api/v1/resources?filter[status]=active&sort=-created_at
```

## Response Best Practices

### 1. Consistent Response Structure

Always return predictable response format:
- Success indicator
- Data payload
- Metadata (pagination, etc.)

### 2. Include Metadata

```json
{
  "success": true,
  "data": [...],
  "meta": {
    "total": 100,
    "page": 1,
    "limit": 50
  }
}
```

### 3. Use HTTP Status Codes Correctly

- 2xx for success
- 4xx for client errors
- 5xx for server errors

## Performance Best Practices

### 1. Enable Compression

```http
Accept-Encoding: gzip, deflate
```

### 2. Use ETags for Caching

```http
ETag: "33a64df551425fcc55e4d42a148795d9f25f89d4"
If-None-Match: "33a64df551425fcc55e4d42a148795d9f25f89d4"
```

### 3. Implement Rate Limiting

- Respect rate limit headers
- Implement exponential backoff
- Cache responses when appropriate

### 4. Batch Requests When Possible

Instead of multiple requests:
```http
POST /api/v1/batch
{
  "requests": [
    {"method": "GET", "path": "/resource/1"},
    {"method": "GET", "path": "/resource/2"}
  ]
}
```

## Security Best Practices

### 1. Always Use HTTPS

Never transmit sensitive data over HTTP.

### 2. Validate All Input

- Check data types
- Validate formats
- Sanitize user input

### 3. Implement Authentication

- Use token-based authentication
- Rotate tokens regularly
- Never expose tokens in URLs

### 4. Rate Limiting

Protect against abuse:
- Per-endpoint limits
- Per-user limits
- Global limits

## Error Handling Best Practices

### 1. Provide Clear Error Messages

```json
{
  "error": {
    "code": "VALIDATION_FAILED",
    "message": "Email format is invalid",
    "field": "email"
  }
}
```

### 2. Include Error Codes

Use consistent error codes across all endpoints.

### 3. Log Errors Server-Side

- Log all errors with context
- Include request IDs for tracking
- Monitor error rates

## Versioning Best Practices

### 1. Version Your API

Use URL versioning:
```
/api/v1/resource
/api/v2/resource
```

### 2. Maintain Backward Compatibility

- Don't remove fields without deprecation
- Add new fields as optional
- Deprecate features gradually

### 3. Document Breaking Changes

Clearly communicate breaking changes in advance.

## Testing Best Practices

### 1. Test All Status Codes

- Success cases (2xx)
- Client errors (4xx)
- Server errors (5xx)

### 2. Test Edge Cases

- Empty responses
- Large payloads
- Invalid input

### 3. Performance Testing

- Load testing
- Stress testing
- Concurrent request testing

---
*Generated by Ecosystem MCP - API Reference Generator*
"""
        
        return {
            'type': 'api_reference',
            'title': 'API Best Practices',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    # ========================================================================
    # Helper Methods
    # ========================================================================
    
    def _format_api_services(self, api_services: List[str]) -> str:
        """Format API services list."""
        if not api_services:
            return "*No API services detected*"
        
        return '\n'.join(f"- **{service}**" for service in api_services)
    
    def _generate_base_urls(self, analysis_report) -> str:
        """Generate base URLs."""
        return """**Development:** `http://localhost:8000`  
**Staging:** `https://staging-api.example.com`  
**Production:** `https://api.example.com`

*Update these URLs based on your deployment configuration.*"""
    
    def _describe_api_architecture(self, analysis_report) -> str:
        """Describe API architecture."""
        if analysis_report.architecture and analysis_report.architecture.primary_pattern:
            pattern = analysis_report.architecture.primary_pattern.name
            if pattern == "MICROSERVICES":
                return "Microservices architecture with independent API services."
            elif pattern == "LAYERED":
                return "Layered architecture with unified API gateway."
        
        return "RESTful API architecture following industry best practices."
    
    def _describe_api_versioning(self, analysis_report) -> str:
        """Describe API versioning."""
        return """API versioning follows URL-based versioning pattern:

- `/api/v1/` - Current stable version
- `/api/v2/` - Next version (if applicable)

Deprecated endpoints will be maintained for at least 6 months."""
    
    def _describe_rate_limiting(self, analysis_report) -> str:
        """Describe rate limiting."""
        return """Rate limits are enforced per API key/user:

- **Standard:** 100 requests/minute
- **Authenticated:** 1000 requests/minute
- **Premium:** 5000 requests/minute

Rate limit headers:
- `X-RateLimit-Limit` - Total allowed requests
- `X-RateLimit-Remaining` - Remaining requests
- `X-RateLimit-Reset` - Reset timestamp"""
    
    def _infer_base_path(self, service) -> str:
        """Infer base path for service."""
        return f"/api/v1/{service.name.lower()}"
    
    def _format_endpoints_detailed(self, service) -> str:
        """Format endpoints with details."""
        if not service.endpoints or len(service.endpoints) == 0:
            return "*Endpoints are being analyzed...*"
        
        lines = []
        
        for endpoint in service.endpoints[:25]:  # Limit to 25
            method = endpoint.get('method', 'GET')
            path = endpoint.get('path', '/')
            desc = endpoint.get('description', 'Endpoint')
            
            lines.append(f"### `{method} {path}`")
            lines.append(f"\n{desc}\n")
            lines.append("**Parameters:**")
            lines.append("- See request examples below\n")
            lines.append("**Response:**")
            lines.append("- See response schemas below\n")
            lines.append("---\n")
        
        return '\n'.join(lines)
    
    def _generate_request_examples(self, service) -> str:
        """Generate request examples."""
        return f"""### Example: Get Resources

```http
GET /api/v1/{service.name.lower()}/resources
Authorization: Bearer YOUR_TOKEN
```

### Example: Create Resource

```http
POST /api/v1/{service.name.lower()}/resources
Authorization: Bearer YOUR_TOKEN
Content-Type: application/json

{{
  "name": "Example Resource",
  "description": "Resource description"
}}
```"""
    
    def _generate_response_schemas(self, service) -> str:
        """Generate response schemas."""
        return """### Success Response

```json
{
  "success": true,
  "data": {
    "id": "123",
    "name": "Example Resource",
    "created_at": "2025-10-21T00:00:00Z"
  }
}
```

### Error Response

```json
{
  "success": false,
  "error": {
    "code": "ERROR_CODE",
    "message": "Error description"
  }
}
```"""
    
    def _detect_auth_methods(self, analysis_report) -> List[str]:
        """Detect authentication methods."""
        # Default to common methods
        return ["Bearer Token", "API Key"]
    
    def _describe_authentication_overview(self, auth_methods: List[str]) -> str:
        """Describe authentication overview."""
        return f"""All API endpoints require authentication unless explicitly marked as public.

**Supported Methods:** {', '.join(auth_methods)}

Authentication ensures:
- Request authorization
- Rate limiting per user
- Audit logging
- Access control"""
    
    def _format_auth_methods(self, auth_methods: List[str]) -> str:
        """Format authentication methods."""
        lines = []
        
        if "Bearer Token" in auth_methods:
            lines.append("""### Bearer Token (JWT)

**Recommended method** for API access.

```http
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```

Tokens are obtained via login endpoint and expire after 24 hours.""")
        
        if "API Key" in auth_methods:
            lines.append("""### API Key

Alternative method for programmatic access.

```http
X-API-Key: your-api-key-here
```

API keys do not expire but can be rotated manually.""")
        
        return '\n\n'.join(lines)

