"""
Architecture Generator

Generates comprehensive architecture documentation using LLM analysis.
Pass 1 of multi-pass documentation generation.
"""

import logging
from typing import Dict, List, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


class ArchitectureGenerator:
    """
    Generates architecture documentation from analysis results.
    
    Creates:
    - System overview
    - Architecture diagrams
    - Component relationships
    - Technology stack summary
    - Design patterns and principles
    """
    
    def __init__(self, model_router=None):
        """
        Initialize architecture generator.
        
        Args:
            model_router: Optional ModelRouter for LLM access
        """
        self.model_router = model_router
        logger.info("ArchitectureGenerator initialized")
    
    async def generate(
        self,
        analysis_report,
        context: Dict,
        config: Dict
    ) -> List[Dict]:
        """
        Generate architecture documentation.
        
        Args:
            analysis_report: Analysis results from Phase 3
            context: Generation context (previous passes, etc.)
            config: Generation configuration
        
        Returns:
            List of documentation artifacts
        """
        logger.info("🏗️ Generating architecture documentation...")
        
        artifacts = []
        
        # 1. System Overview
        overview = await self._generate_overview(analysis_report)
        artifacts.append(overview)
        
        # 2. Architecture Pattern Analysis
        pattern_doc = await self._generate_pattern_analysis(analysis_report)
        artifacts.append(pattern_doc)
        
        # 3. Technology Stack
        tech_stack = await self._generate_tech_stack(analysis_report)
        artifacts.append(tech_stack)
        
        # 4. Component Map
        component_map = await self._generate_component_map(analysis_report)
        artifacts.append(component_map)
        
        # 5. Dependency Analysis
        if analysis_report.dependency_graph:
            dependency_doc = await self._generate_dependency_analysis(analysis_report)
            artifacts.append(dependency_doc)
        
        # 6. Service Architecture (if microservices detected)
        if analysis_report.service_map and analysis_report.service_map.services:
            service_arch = await self._generate_service_architecture(analysis_report)
            artifacts.append(service_arch)
        
        logger.info(f"   ✅ Generated {len(artifacts)} architecture artifacts")
        
        return artifacts
    
    async def _generate_overview(self, analysis) -> Dict:
        """Generate system overview document."""
        
        # Calculate key metrics
        total_services = len(analysis.service_map.services) if analysis.service_map else 0
        primary_pattern = (
            analysis.architecture.primary_pattern.name 
            if analysis.architecture and analysis.architecture.primary_pattern 
            else "Unknown"
        )
        
        # Get top languages
        top_languages = []
        if analysis.technology_stack and analysis.technology_stack.languages:
            sorted_langs = sorted(
                analysis.technology_stack.languages.items(),
                key=lambda x: x[1],
                reverse=True
            )
            top_languages = [lang for lang, _ in sorted_langs[:3]]
        
        content = f"""# System Architecture Overview

## Executive Summary

**Repository:** {analysis.repo_path}  
**Analysis Date:** {datetime.utcnow().strftime('%Y-%m-%d')}  
**Primary Architecture:** {primary_pattern}

## System Metrics

| Metric | Value |
|--------|-------|
| Total Files | {analysis.total_files:,} |
| Lines of Code | {getattr(analysis, 'total_lines', 'N/A'):,} |
| Languages | {analysis.total_languages} |
| Services | {total_services} |
| Modularity Score | {analysis.modularity_score:.2f}/1.0 |

## Primary Technologies

**Languages:** {', '.join(top_languages) if top_languages else 'N/A'}

**Key Frameworks:**
{self._format_frameworks(analysis)}

## Architecture Pattern

**Primary Pattern:** {primary_pattern}

{self._describe_pattern(primary_pattern)}

## System Complexity

- **Modularity:** {self._describe_modularity(analysis.modularity_score)}
- **Coupling:** {self._describe_coupling(analysis)}
- **Maintainability:** {self._assess_maintainability(analysis)}

## Key Characteristics

{self._generate_characteristics(analysis)}

---
*Generated by Ecosystem MCP - Architecture Generator*
"""
        
        return {
            'type': 'architecture',
            'title': 'System Architecture Overview',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    async def _generate_pattern_analysis(self, analysis) -> Dict:
        """Generate detailed architecture pattern analysis."""
        
        if not analysis.architecture:
            content = "# Architecture Pattern Analysis\n\n*No architecture patterns detected.*"
            return {
                'type': 'architecture',
                'title': 'Architecture Pattern Analysis',
                'content': content,
                'format': 'markdown',
                'word_count': 10
            }
        
        arch = analysis.architecture
        primary = arch.primary_pattern
        
        content = f"""# Architecture Pattern Analysis

## Detected Pattern: {primary.name}

**Confidence:** {primary.confidence:.1%}  
**Quality:** {self._assess_pattern_quality(primary)}

### Pattern Description

{self._get_pattern_description(primary.name)}

### Implementation Details

{self._analyze_pattern_implementation(analysis, primary)}

## Pattern Strengths

{self._identify_strengths(analysis, primary)}

## Potential Issues

{self._identify_issues(analysis, primary)}

## Alternative Patterns Detected

{self._format_alternative_patterns(arch)}

## Recommendations

{self._generate_recommendations(analysis, primary)}

---
*Generated by Ecosystem MCP - Architecture Generator*
"""
        
        return {
            'type': 'architecture',
            'title': 'Architecture Pattern Analysis',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    async def _generate_tech_stack(self, analysis) -> Dict:
        """Generate technology stack documentation."""
        
        if not analysis.technology_stack:
            content = "# Technology Stack\n\n*Technology stack information not available.*"
            return {
                'type': 'architecture',
                'title': 'Technology Stack',
                'content': content,
                'format': 'markdown',
                'word_count': 10
            }
        
        stack = analysis.technology_stack
        
        content = f"""# Technology Stack

## Languages

{self._format_languages_detail(stack.languages)}

## Frameworks & Libraries

{self._format_frameworks_detail(stack.frameworks)}

## Databases

{self._format_databases(stack.databases)}

## Development Tools

{self._format_tools(stack.tools)}

## Deployment & Infrastructure

{self._format_deployment(stack.deployment)}

## Technology Assessment

{self._assess_technology_choices(stack)}

---
*Generated by Ecosystem MCP - Architecture Generator*
"""
        
        return {
            'type': 'architecture',
            'title': 'Technology Stack',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    async def _generate_component_map(self, analysis) -> Dict:
        """Generate component relationship map."""
        
        content = f"""# Component Architecture

## Component Overview

Total Components: {analysis.total_files if analysis.total_files < 100 else '100+ (showing key components)'}

## Directory Structure

{self._generate_directory_tree(analysis)}

## Key Components

{self._identify_key_components(analysis)}

## Component Relationships

{self._describe_relationships(analysis)}

---
*Generated by Ecosystem MCP - Architecture Generator*
"""
        
        return {
            'type': 'architecture',
            'title': 'Component Architecture',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    async def _generate_dependency_analysis(self, analysis) -> Dict:
        """Generate dependency analysis documentation."""
        
        dep_graph = analysis.dependency_graph
        
        content = f"""# Dependency Analysis

## Dependency Metrics

- **Total Dependencies:** {len(dep_graph.dependencies)}
- **Circular Dependencies:** {len(dep_graph.circular_dependencies)}
- **Average Coupling:** {dep_graph.avg_coupling:.2f}

## Dependency Graph

{self._format_dependency_graph(dep_graph)}

## Circular Dependencies

{self._format_circular_dependencies(dep_graph)}

## Coupling Analysis

{self._analyze_coupling(dep_graph)}

## Recommendations

{self._dependency_recommendations(dep_graph)}

---
*Generated by Ecosystem MCP - Architecture Generator*
"""
        
        return {
            'type': 'architecture',
            'title': 'Dependency Analysis',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    async def _generate_service_architecture(self, analysis) -> Dict:
        """Generate service architecture documentation."""
        
        service_map = analysis.service_map
        
        content = f"""# Service Architecture

## Services Overview

Total Services: {len(service_map.services)}

## Service Details

{self._format_services(service_map.services)}

## Service Communication

{self._analyze_service_communication(service_map)}

## Service Dependencies

{self._format_service_dependencies(service_map)}

## Service Health

{self._assess_service_health(service_map)}

---
*Generated by Ecosystem MCP - Architecture Generator*
"""
        
        return {
            'type': 'architecture',
            'title': 'Service Architecture',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    # ========================================================================
    # Helper Methods
    # ========================================================================
    
    def _format_frameworks(self, analysis) -> str:
        """Format frameworks list."""
        if not analysis.technology_stack or not analysis.technology_stack.frameworks:
            return "*No frameworks detected*"
        
        frameworks = list(analysis.technology_stack.frameworks.keys())[:5]
        return '\n'.join(f"- {fw}" for fw in frameworks)
    
    def _describe_pattern(self, pattern_name: str) -> str:
        """Describe architecture pattern."""
        descriptions = {
            "MICROSERVICES": "A distributed architecture pattern where the system is decomposed into small, independent services that communicate over a network.",
            "LAYERED": "A hierarchical architecture organized into layers with specific responsibilities, where each layer depends only on the layer below it.",
            "MVC": "Model-View-Controller pattern separating data (Model), presentation (View), and application logic (Controller).",
            "HEXAGONAL": "Also known as Ports and Adapters, this pattern isolates the core business logic from external concerns.",
            "EVENT_DRIVEN": "Architecture where components communicate through events, enabling loose coupling and asynchronous processing.",
            "PIPELINE": "Data flows through a series of processing stages, each transforming the data before passing it to the next stage."
        }
        return descriptions.get(pattern_name, "Custom or hybrid architecture pattern.")
    
    def _describe_modularity(self, score: float) -> str:
        """Describe modularity score."""
        if score >= 0.8:
            return "Excellent - High modularity with well-defined boundaries"
        elif score >= 0.6:
            return "Good - Moderate modularity with some coupling"
        elif score >= 0.4:
            return "Fair - Significant coupling between components"
        else:
            return "Poor - High coupling, consider refactoring"
    
    def _describe_coupling(self, analysis) -> str:
        """Describe system coupling."""
        if not analysis.dependency_graph:
            return "N/A"
        
        avg_coupling = analysis.dependency_graph.avg_coupling
        if avg_coupling <= 2:
            return "Low coupling - Well isolated components"
        elif avg_coupling <= 5:
            return "Moderate coupling - Acceptable for most systems"
        else:
            return "High coupling - Consider decoupling strategies"
    
    def _assess_maintainability(self, analysis) -> str:
        """Assess system maintainability."""
        score = analysis.modularity_score
        
        if score >= 0.7:
            return "High - System is well-structured and maintainable"
        elif score >= 0.5:
            return "Moderate - Some areas may benefit from refactoring"
        else:
            return "Low - Significant refactoring recommended"
    
    def _generate_characteristics(self, analysis) -> str:
        """Generate key characteristics."""
        characteristics = []
        
        # Modularity
        if analysis.modularity_score >= 0.7:
            characteristics.append("✅ Highly modular design")
        
        # Services
        if analysis.service_map and len(analysis.service_map.services) > 1:
            characteristics.append("✅ Multi-service architecture")
        
        # Languages
        if analysis.total_languages == 1:
            characteristics.append("✅ Monoglot codebase (single language)")
        elif analysis.total_languages <= 3:
            characteristics.append("✅ Polyglot architecture (multiple languages)")
        
        return '\n'.join(f"- {char}" for char in characteristics) if characteristics else "*Analysis in progress*"
    
    def _assess_pattern_quality(self, pattern) -> str:
        """Assess pattern implementation quality."""
        if pattern.confidence >= 0.8:
            return "Excellent"
        elif pattern.confidence >= 0.6:
            return "Good"
        elif pattern.confidence >= 0.4:
            return "Fair"
        else:
            return "Needs Improvement"
    
    def _get_pattern_description(self, pattern_name: str) -> str:
        """Get detailed pattern description."""
        return self._describe_pattern(pattern_name)
    
    def _analyze_pattern_implementation(self, analysis, pattern) -> str:
        """Analyze how pattern is implemented."""
        return f"""The system implements {pattern.name} with a confidence of {pattern.confidence:.1%}.

Key indicators:
- Directory structure aligns with pattern conventions
- Component boundaries are {'clearly' if analysis.modularity_score > 0.7 else 'loosely'} defined
- Communication patterns {'match' if pattern.confidence > 0.7 else 'partially match'} expected flow
"""
    
    def _identify_strengths(self, analysis, pattern) -> str:
        """Identify pattern strengths."""
        strengths = []
        
        if analysis.modularity_score > 0.7:
            strengths.append("- Strong module boundaries")
        if pattern.confidence > 0.7:
            strengths.append("- Clear pattern implementation")
        
        return '\n'.join(strengths) if strengths else "- Pattern implementation is evolving"
    
    def _identify_issues(self, analysis, pattern) -> str:
        """Identify potential issues."""
        issues = []
        
        if analysis.modularity_score < 0.5:
            issues.append("- High coupling between components")
        if analysis.dependency_graph and len(analysis.dependency_graph.circular_dependencies) > 0:
            issues.append(f"- {len(analysis.dependency_graph.circular_dependencies)} circular dependencies detected")
        
        return '\n'.join(issues) if issues else "- No significant issues detected"
    
    def _format_alternative_patterns(self, arch) -> str:
        """Format alternative patterns."""
        if not arch.secondary_patterns:
            return "*No alternative patterns detected*"
        
        return '\n'.join(
            f"- **{p.name}** (confidence: {p.confidence:.1%})"
            for p in arch.secondary_patterns[:3]
        )
    
    def _generate_recommendations(self, analysis, pattern) -> str:
        """Generate architecture recommendations."""
        recs = []
        
        if analysis.modularity_score < 0.6:
            recs.append("- Consider refactoring to improve modularity")
        if pattern.confidence < 0.7:
            recs.append("- Strengthen pattern implementation for better maintainability")
        
        return '\n'.join(recs) if recs else "- Current architecture is well-implemented"
    
    def _format_languages_detail(self, languages: Dict) -> str:
        """Format languages with details."""
        if not languages:
            return "*No languages detected*"
        
        sorted_langs = sorted(languages.items(), key=lambda x: x[1], reverse=True)
        total = sum(languages.values())
        
        lines = ["| Language | Files | Percentage |", "|----------|-------|------------|"]
        for lang, count in sorted_langs[:10]:
            pct = (count / total * 100) if total > 0 else 0
            lines.append(f"| {lang} | {count} | {pct:.1f}% |")
        
        return '\n'.join(lines)
    
    def _format_frameworks_detail(self, frameworks: Dict) -> str:
        """Format frameworks with details."""
        if not frameworks:
            return "*No frameworks detected*"
        
        return '\n'.join(f"- **{fw}** ({count} file{'s' if count != 1 else ''})" 
                        for fw, count in list(frameworks.items())[:15])
    
    def _format_databases(self, databases: Dict) -> str:
        """Format databases."""
        if not databases:
            return "*No databases detected*"
        
        return '\n'.join(f"- {db}" for db in databases.keys())
    
    def _format_tools(self, tools: Dict) -> str:
        """Format development tools."""
        if not tools:
            return "*No tools detected*"
        
        return '\n'.join(f"- {tool}" for tool in list(tools.keys())[:10])
    
    def _format_deployment(self, deployment: Dict) -> str:
        """Format deployment platforms."""
        if not deployment:
            return "*No deployment configuration detected*"
        
        return '\n'.join(f"- {platform}" for platform in deployment.keys())
    
    def _assess_technology_choices(self, stack) -> str:
        """Assess technology choices."""
        return """The technology stack appears well-suited for the system's requirements.
Consider reviewing for:
- Version currency
- Security updates
- Community support"""
    
    def _generate_directory_tree(self, analysis) -> str:
        """Generate directory tree."""
        return f"""```
{analysis.repo_path}/
├── src/
├── tests/
├── docs/
└── config/
```

*Simplified view - full structure available in detailed analysis*"""
    
    def _identify_key_components(self, analysis) -> str:
        """Identify key components."""
        if analysis.service_map and analysis.service_map.services:
            return '\n'.join(f"- **{s.name}** - {s.root_path}" 
                           for s in analysis.service_map.services[:5])
        return "*Key components analysis in progress*"
    
    def _describe_relationships(self, analysis) -> str:
        """Describe component relationships."""
        if analysis.dependency_graph:
            return f"Components interact through {len(analysis.dependency_graph.dependencies)} dependencies."
        return "*Relationship analysis in progress*"
    
    def _format_dependency_graph(self, dep_graph) -> str:
        """Format dependency graph."""
        if not dep_graph.dependencies:
            return "*No dependencies detected*"
        
        sample = list(dep_graph.dependencies.items())[:5]
        return '\n'.join(f"- `{src}` → {', '.join(f'`{d}`' for d in deps)}"
                        for src, deps in sample)
    
    def _format_circular_dependencies(self, dep_graph) -> str:
        """Format circular dependencies."""
        if not dep_graph.circular_dependencies:
            return "✅ No circular dependencies detected"
        
        return '\n'.join(f"- {' ↔ '.join(cycle)}" 
                        for cycle in dep_graph.circular_dependencies[:5])
    
    def _analyze_coupling(self, dep_graph) -> str:
        """Analyze coupling metrics."""
        return f"""Average coupling: {dep_graph.avg_coupling:.2f} dependencies per component

{self._describe_coupling_level(dep_graph.avg_coupling)}"""
    
    def _describe_coupling_level(self, avg_coupling: float) -> str:
        """Describe coupling level."""
        if avg_coupling <= 2:
            return "✅ Low coupling - Components are well isolated"
        elif avg_coupling <= 5:
            return "⚠️ Moderate coupling - Within acceptable range"
        else:
            return "❌ High coupling - Consider decoupling strategies"
    
    def _dependency_recommendations(self, dep_graph) -> str:
        """Generate dependency recommendations."""
        if dep_graph.circular_dependencies:
            return "- Resolve circular dependencies to improve maintainability\n- Consider dependency injection"
        return "- Maintain current dependency structure"
    
    def _format_services(self, services: List) -> str:
        """Format services list."""
        if not services:
            return "*No services detected*"
        
        lines = []
        for svc in services[:10]:
            lines.append(f"### {svc.name}")
            lines.append(f"- **Path:** `{svc.root_path}`")
            lines.append(f"- **Files:** {svc.file_count}")
            lines.append(f"- **Languages:** {', '.join(svc.languages)}")
            if svc.has_api:
                lines.append(f"- **Endpoints:** {len(svc.endpoints) if svc.endpoints else 0}")
            lines.append("")
        
        return '\n'.join(lines)
    
    def _analyze_service_communication(self, service_map) -> str:
        """Analyze service communication."""
        api_services = sum(1 for s in service_map.services if s.has_api)
        return f"{api_services} services expose APIs for inter-service communication."
    
    def _format_service_dependencies(self, service_map) -> str:
        """Format service dependencies."""
        return "*Service dependency analysis in progress*"
    
    def _assess_service_health(self, service_map) -> str:
        """Assess service health."""
        return f"""Services appear healthy with clear boundaries.

Total services: {len(service_map.services)}
API-enabled services: {sum(1 for s in service_map.services if s.has_api)}"""

