"""
Component Generator

Generates detailed component-level documentation.
Pass 2 of multi-pass documentation generation.
"""

import logging
from typing import Dict, List, Optional
from pathlib import Path

logger = logging.getLogger(__name__)


class ComponentGenerator:
    """
    Generates component-level documentation from analysis results.
    
    Creates documentation for:
    - Individual services
    - Key modules
    - Component responsibilities
    - Internal architecture
    - API endpoints
    """
    
    def __init__(self, model_router=None):
        """
        Initialize component generator.
        
        Args:
            model_router: Optional ModelRouter for LLM access
        """
        self.model_router = model_router
        logger.info("ComponentGenerator initialized")
    
    async def generate(
        self,
        analysis_report,
        context: Dict,
        config: Dict
    ) -> List[Dict]:
        """
        Generate component documentation.
        
        Args:
            analysis_report: Analysis results from Phase 3
            context: Generation context (previous passes, etc.)
            config: Generation configuration
        
        Returns:
            List of documentation artifacts
        """
        logger.info("🧩 Generating component documentation...")
        
        artifacts = []
        
        # Generate service-level documentation
        if analysis_report.service_map and analysis_report.service_map.services:
            for service in analysis_report.service_map.services:
                service_doc = await self._generate_service_doc(
                    service,
                    analysis_report,
                    context
                )
                artifacts.append(service_doc)
        else:
            # Generate module-level documentation for non-service architectures
            module_docs = await self._generate_module_docs(
                analysis_report,
                context
            )
            artifacts.extend(module_docs)
        
        logger.info(f"   ✅ Generated {len(artifacts)} component artifacts")
        
        return artifacts
    
    async def _generate_service_doc(
        self,
        service,
        analysis_report,
        context: Dict
    ) -> Dict:
        """Generate documentation for a single service."""
        
        logger.info(f"   📦 Documenting service: {service.name}")
        
        content = f"""# Service: {service.name}

## Overview

**Service Name:** {service.name}  
**Location:** `{service.root_path}`  
**Type:** {"API Service" if service.has_api else "Internal Service"}

## Purpose

{self._infer_service_purpose(service, analysis_report)}

## Metrics

| Metric | Value |
|--------|-------|
| Total Files | {service.file_count} |
| Languages | {', '.join(service.languages)} |
| Frameworks | {', '.join(service.frameworks) if service.frameworks else 'None'} |
| API Endpoints | {len(service.endpoints) if service.endpoints else 0} |
| Database Access | {self._detect_database_access(service)} |

## Architecture

### Technology Stack

**Primary Languages:**
{self._format_service_languages(service)}

**Frameworks:**
{self._format_service_frameworks(service)}

### Internal Structure

{self._analyze_service_structure(service)}

## API Endpoints

{self._format_service_endpoints(service)}

## Dependencies

{self._analyze_service_dependencies(service, analysis_report)}

## Data Flow

{self._describe_data_flow(service, analysis_report)}

## Configuration

{self._analyze_configuration(service)}

## Health & Monitoring

{self._analyze_health_monitoring(service)}

## Deployment

{self._analyze_deployment(service)}

## Development

### Local Setup

{self._generate_local_setup(service)}

### Testing

{self._analyze_testing(service)}

## Maintenance Notes

{self._generate_maintenance_notes(service, analysis_report)}

---
*Generated by Ecosystem MCP - Component Generator*
"""
        
        return {
            'type': 'component',
            'title': f'Service: {service.name}',
            'component_name': service.name,
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    async def _generate_module_docs(
        self,
        analysis_report,
        context: Dict
    ) -> List[Dict]:
        """Generate documentation for key modules (non-service architecture)."""
        
        logger.info("   📦 Documenting key modules...")
        
        artifacts = []
        
        # Identify key directories
        key_dirs = self._identify_key_directories(analysis_report)
        
        for dir_path, dir_info in list(key_dirs.items())[:10]:  # Limit to top 10
            module_doc = await self._generate_module_doc(
                dir_path,
                dir_info,
                analysis_report
            )
            artifacts.append(module_doc)
        
        return artifacts
    
    async def _generate_module_doc(
        self,
        dir_path: str,
        dir_info: Dict,
        analysis_report
    ) -> Dict:
        """Generate documentation for a single module."""
        
        module_name = Path(dir_path).name
        
        content = f"""# Module: {module_name}

## Overview

**Module Path:** `{dir_path}`  
**Files:** {dir_info.get('file_count', 0)}  
**Size:** {dir_info.get('size_kb', 0)} KB

## Purpose

{self._infer_module_purpose(module_name, dir_info)}

## Structure

{self._analyze_module_structure(dir_path, dir_info)}

## Key Files

{self._list_key_files(dir_info)}

## Dependencies

{self._analyze_module_dependencies(dir_path, analysis_report)}

---
*Generated by Ecosystem MCP - Component Generator*
"""
        
        return {
            'type': 'component',
            'title': f'Module: {module_name}',
            'component_name': module_name,
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    # ========================================================================
    # Helper Methods
    # ========================================================================
    
    def _infer_service_purpose(self, service, analysis_report) -> str:
        """Infer service purpose from name and characteristics."""
        name_lower = service.name.lower()
        
        # API services
        if service.has_api:
            if 'api' in name_lower or 'gateway' in name_lower:
                return "API gateway service providing external interface to the system."
            return f"REST API service handling {service.name}-related operations."
        
        # Worker services
        if 'worker' in name_lower or 'job' in name_lower:
            return "Background worker service processing asynchronous tasks."
        
        # Dashboard/UI services
        if 'dashboard' in name_lower or 'ui' in name_lower or 'frontend' in name_lower:
            return "Frontend service providing user interface and visualization."
        
        # Database services
        if 'db' in name_lower or 'database' in name_lower:
            return "Database service managing data persistence."
        
        # Default
        return f"Internal service providing {service.name} functionality."
    
    def _detect_database_access(self, service) -> str:
        """Detect if service has database access."""
        # Check for database-related frameworks
        db_frameworks = ['sqlalchemy', 'psycopg2', 'pymongo', 'redis']
        
        if service.frameworks:
            for fw in service.frameworks:
                if any(db in fw.lower() for db in db_frameworks):
                    return "Yes"
        
        return "Unknown"
    
    def _format_service_languages(self, service) -> str:
        """Format service languages."""
        if not service.languages:
            return "*No languages detected*"
        
        return '\n'.join(f"- {lang}" for lang in service.languages)
    
    def _format_service_frameworks(self, service) -> str:
        """Format service frameworks."""
        if not service.frameworks:
            return "*No frameworks detected*"
        
        return '\n'.join(f"- {fw}" for fw in service.frameworks)
    
    def _analyze_service_structure(self, service) -> str:
        """Analyze service internal structure."""
        return f"""The service is organized under `{service.root_path}` with {service.file_count} files.

**Organization:**
- Source code: Primary implementation files
- Configuration: Service-specific settings
- Tests: Unit and integration tests (if present)

**Design Pattern:**
- {self._detect_service_pattern(service)}
"""
    
    def _detect_service_pattern(self, service) -> str:
        """Detect service design pattern."""
        if 'fastapi' in [f.lower() for f in (service.frameworks or [])]:
            return "FastAPI application with async request handling"
        elif 'flask' in [f.lower() for f in (service.frameworks or [])]:
            return "Flask application with synchronous request handling"
        elif 'streamlit' in [f.lower() for f in (service.frameworks or [])]:
            return "Streamlit dashboard with reactive components"
        else:
            return "Standard service architecture"
    
    def _format_service_endpoints(self, service) -> str:
        """Format service API endpoints."""
        if not service.has_api or not service.endpoints:
            return "*No API endpoints exposed*"
        
        if len(service.endpoints) == 0:
            return "*API endpoints present but not yet analyzed*"
        
        lines = ["| Method | Path | Description |", "|--------|------|-------------|"]
        
        for endpoint in service.endpoints[:20]:  # Limit to 20 endpoints
            method = endpoint.get('method', 'GET')
            path = endpoint.get('path', '/')
            desc = endpoint.get('description', 'Endpoint')
            lines.append(f"| {method} | `{path}` | {desc} |")
        
        if len(service.endpoints) > 20:
            lines.append(f"| ... | ... | *{len(service.endpoints) - 20} more endpoints* |")
        
        return '\n'.join(lines)
    
    def _analyze_service_dependencies(self, service, analysis_report) -> str:
        """Analyze service dependencies."""
        if not analysis_report.dependency_graph:
            return "*Dependency analysis not available*"
        
        # Check if service has dependencies
        service_deps = []
        # dependency_graph.edges is a list of Dependency objects
        for edge in analysis_report.dependency_graph.edges:
            if service.root_path in edge.source_file:
                service_deps.append(edge.target_file)
        
        if not service_deps:
            return "*No external dependencies detected*"
        
        unique_deps = set(service_deps)
        return '\n'.join(f"- `{dep}`" for dep in list(unique_deps)[:15])
    
    def _describe_data_flow(self, service, analysis_report) -> str:
        """Describe service data flow."""
        if service.has_api:
            return """```
Client Request → API Endpoints → Business Logic → Data Layer → Response
```

The service follows a standard request-response pattern with clear separation of concerns."""
        else:
            return """```
Input → Processing → Output
```

Internal service with task-based processing."""
    
    def _analyze_configuration(self, service) -> str:
        """Analyze service configuration."""
        return """Configuration is managed through:
- Environment variables
- Configuration files (if present)
- Default settings

**Key Configuration Areas:**
- Database connection
- External service URLs
- Feature flags
- Resource limits
"""
    
    def _analyze_health_monitoring(self, service) -> str:
        """Analyze health monitoring."""
        if service.has_api:
            return """**Health Endpoints:**
- `/health` - Basic health check
- `/ready` - Readiness probe

**Monitoring:**
- Request/response logging
- Error tracking
- Performance metrics
"""
        else:
            return """**Monitoring:**
- Process health
- Resource utilization
- Error logging
"""
    
    def _analyze_deployment(self, service) -> str:
        """Analyze deployment configuration."""
        return f"""**Deployment Method:**
- Containerized (Docker)
- Service: `{service.name}`

**Requirements:**
- Runtime: {', '.join(service.languages)}
- Dependencies: Managed via package manager

**Scaling:**
- Horizontal scaling supported
- Stateless design (recommended)
"""
    
    def _generate_local_setup(self, service) -> str:
        """Generate local setup instructions."""
        primary_lang = service.languages[0] if service.languages else 'unknown'
        
        if 'python' in primary_lang.lower():
            return """```bash
# Install dependencies
pip install -r requirements.txt

# Run service
python main.py
```"""
        elif 'javascript' in primary_lang.lower() or 'typescript' in primary_lang.lower():
            return """```bash
# Install dependencies
npm install

# Run service
npm start
```"""
        else:
            return """```bash
# See service-specific README for setup instructions
```"""
    
    def _analyze_testing(self, service) -> str:
        """Analyze testing approach."""
        return f"""**Test Coverage:**
- Unit tests: Core business logic
- Integration tests: External dependencies
- API tests: Endpoint validation (if applicable)

**Running Tests:**
```bash
# Run all tests
pytest tests/
```

**Test Files:** Located in service test directory"""
    
    def _generate_maintenance_notes(self, service, analysis_report) -> str:
        """Generate maintenance notes."""
        notes = []
        
        # Check modularity
        if analysis_report.modularity_score < 0.6:
            notes.append("- ⚠️ Consider improving modularity for easier maintenance")
        
        # Check service size
        if service.file_count > 100:
            notes.append("- ⚠️ Large service - consider splitting into smaller services")
        
        # Check API complexity
        if service.endpoints and len(service.endpoints) > 50:
            notes.append("- ⚠️ High number of endpoints - consider API versioning")
        
        if not notes:
            notes.append("- ✅ Service is well-structured and maintainable")
        
        return '\n'.join(notes)
    
    def _identify_key_directories(self, analysis_report) -> Dict:
        """Identify key directories in the repository."""
        # Placeholder - would analyze file structure
        return {
            f"{analysis_report.repo_path}/src": {
                'file_count': 50,
                'size_kb': 500
            },
            f"{analysis_report.repo_path}/tests": {
                'file_count': 30,
                'size_kb': 200
            }
        }
    
    def _infer_module_purpose(self, module_name: str, dir_info: Dict) -> str:
        """Infer module purpose from name."""
        name_lower = module_name.lower()
        
        if name_lower == 'src':
            return "Main source code directory containing core application logic."
        elif name_lower == 'tests':
            return "Test suite directory containing unit and integration tests."
        elif name_lower == 'docs':
            return "Documentation directory containing project documentation."
        elif name_lower == 'config':
            return "Configuration directory containing application settings."
        elif 'api' in name_lower:
            return "API layer providing external interface."
        elif 'models' in name_lower or 'model' in name_lower:
            return "Data models and schemas."
        elif 'utils' in name_lower or 'helpers' in name_lower:
            return "Utility functions and helper modules."
        else:
            return f"Module providing {module_name} functionality."
    
    def _analyze_module_structure(self, dir_path: str, dir_info: Dict) -> str:
        """Analyze module structure."""
        return f"""The module contains {dir_info.get('file_count', 0)} files organized for maintainability.

**Key Areas:**
- Core implementation files
- Supporting utilities
- Configuration (if present)
"""
    
    def _list_key_files(self, dir_info: Dict) -> str:
        """List key files in module."""
        # Placeholder - would list actual files
        return """*Key files identified through analysis*

Common patterns:
- `__init__.py` - Module initialization
- `main.py` or `app.py` - Entry point
- `config.py` - Configuration
- `utils.py` - Utilities
"""
    
    def _analyze_module_dependencies(self, dir_path: str, analysis_report) -> str:
        """Analyze module dependencies."""
        if not analysis_report.dependency_graph:
            return "*Dependency analysis not available*"
        
        return """Dependencies are managed through standard package management.

**Types:**
- Internal: Other modules in the project
- External: Third-party packages
"""

