"""
Examples Generator

Generates usage examples and integration guides.
Pass 4 of multi-pass documentation generation.
"""

import logging
from typing import Dict, List

logger = logging.getLogger(__name__)


class ExamplesGenerator:
    """
    Generates usage examples and guides from analysis results.
    
    Creates:
    - Quick start guide
    - Usage examples
    - Integration guides
    - Code samples
    - Common workflows
    """
    
    def __init__(self, model_router=None):
        """
        Initialize examples generator.
        
        Args:
            model_router: Optional ModelRouter for LLM access
        """
        self.model_router = model_router
        logger.info("ExamplesGenerator initialized")
    
    async def generate(
        self,
        analysis_report,
        context: Dict,
        config: Dict
    ) -> List[Dict]:
        """
        Generate examples and guides.
        
        Args:
            analysis_report: Analysis results from Phase 3
            context: Generation context (previous passes, etc.)
            config: Generation configuration
        
        Returns:
            List of documentation artifacts
        """
        logger.info("📚 Generating examples and guides...")
        
        artifacts = []
        
        # 1. Quick Start Guide
        quickstart = await self._generate_quickstart(analysis_report)
        artifacts.append(quickstart)
        
        # 2. Usage Examples
        usage = await self._generate_usage_examples(analysis_report)
        artifacts.append(usage)
        
        # 3. Integration Guide
        integration = await self._generate_integration_guide(analysis_report)
        artifacts.append(integration)
        
        # 4. Common Workflows
        workflows = await self._generate_workflows(analysis_report)
        artifacts.append(workflows)
        
        logger.info(f"   ✅ Generated {len(artifacts)} example artifacts")
        
        return artifacts
    
    async def _generate_quickstart(self, analysis) -> Dict:
        """Generate quick start guide."""
        
        primary_lang = self._get_primary_language(analysis)
        
        content = f"""# Quick Start Guide

## Prerequisites

{self._generate_prerequisites(analysis)}

## Installation

{self._generate_installation_steps(analysis, primary_lang)}

## Configuration

{self._generate_configuration_steps(analysis)}

## Running the Application

{self._generate_run_steps(analysis, primary_lang)}

## Verify Installation

{self._generate_verification_steps(analysis)}

## Next Steps

- Read the [Architecture Overview](./architecture-overview.md)
- Explore [API Reference](./api-reference.md)
- Review [Usage Examples](./usage-examples.md)

---
*Generated by Ecosystem MCP - Examples Generator*
"""
        
        return {
            'type': 'examples',
            'title': 'Quick Start Guide',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    async def _generate_usage_examples(self, analysis) -> Dict:
        """Generate usage examples."""
        
        has_api = self._has_api_services(analysis)
        primary_lang = self._get_primary_language(analysis)
        
        content = f"""# Usage Examples

## Basic Usage

{self._generate_basic_usage(analysis, primary_lang)}

{self._generate_api_examples(analysis) if has_api else ''}

## Advanced Usage

{self._generate_advanced_usage(analysis, primary_lang)}

## Code Samples

{self._generate_code_samples(analysis, primary_lang)}

## Testing Examples

{self._generate_testing_examples(analysis, primary_lang)}

---
*Generated by Ecosystem MCP - Examples Generator*
"""
        
        return {
            'type': 'examples',
            'title': 'Usage Examples',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    async def _generate_integration_guide(self, analysis) -> Dict:
        """Generate integration guide."""
        
        content = f"""# Integration Guide

## Overview

This guide shows how to integrate with the system.

## Integration Methods

{self._describe_integration_methods(analysis)}

## Authentication Setup

{self._generate_auth_setup(analysis)}

## SDK Usage

{self._generate_sdk_usage(analysis)}

## Webhook Integration

{self._generate_webhook_integration(analysis)}

## Error Handling

{self._generate_integration_error_handling()}

## Best Practices

{self._generate_integration_best_practices()}

---
*Generated by Ecosystem MCP - Examples Generator*
"""
        
        return {
            'type': 'examples',
            'title': 'Integration Guide',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    async def _generate_workflows(self, analysis) -> Dict:
        """Generate common workflows."""
        
        content = f"""# Common Workflows

## Workflow 1: Basic Setup

{self._generate_setup_workflow(analysis)}

## Workflow 2: Data Processing

{self._generate_processing_workflow(analysis)}

## Workflow 3: API Integration

{self._generate_api_workflow(analysis)}

## Workflow 4: Deployment

{self._generate_deployment_workflow(analysis)}

## Workflow 5: Monitoring & Debugging

{self._generate_monitoring_workflow(analysis)}

---
*Generated by Ecosystem MCP - Examples Generator*
"""
        
        return {
            'type': 'examples',
            'title': 'Common Workflows',
            'content': content,
            'format': 'markdown',
            'word_count': len(content.split())
        }
    
    # ========================================================================
    # Helper Methods
    # ========================================================================
    
    def _get_primary_language(self, analysis) -> str:
        """Get primary programming language."""
        if analysis.technology_stack and analysis.technology_stack.languages:
            langs = sorted(
                analysis.technology_stack.languages.items(),
                key=lambda x: x[1],
                reverse=True
            )
            return langs[0][0] if langs else "Python"
        return "Python"
    
    def _has_api_services(self, analysis) -> bool:
        """Check if system has API services."""
        if not analysis.service_map:
            return False
        return any(s.has_api for s in analysis.service_map.services)
    
    def _generate_prerequisites(self, analysis) -> str:
        """Generate prerequisites."""
        primary_lang = self._get_primary_language(analysis)
        
        if "Python" in primary_lang:
            return """- Python 3.8 or higher
- pip package manager
- Virtual environment (recommended)
- Docker (optional, for containerized deployment)"""
        elif "JavaScript" in primary_lang or "TypeScript" in primary_lang:
            return """- Node.js 14 or higher
- npm or yarn package manager
- Docker (optional, for containerized deployment)"""
        else:
            return """- Check project README for specific requirements
- Docker (optional, for containerized deployment)"""
    
    def _generate_installation_steps(self, analysis, primary_lang: str) -> str:
        """Generate installation steps."""
        if "Python" in primary_lang:
            return """### 1. Clone the repository

```bash
git clone <repository-url>
cd <project-directory>
```

### 2. Create virtual environment

```bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\\Scripts\\activate
```

### 3. Install dependencies

```bash
pip install -r requirements.txt
```"""
        elif "JavaScript" in primary_lang or "TypeScript" in primary_lang:
            return """### 1. Clone the repository

```bash
git clone <repository-url>
cd <project-directory>
```

### 2. Install dependencies

```bash
npm install
# or
yarn install
```"""
        else:
            return """### 1. Clone the repository

```bash
git clone <repository-url>
cd <project-directory>
```

### 2. Follow project-specific installation instructions in README"""
    
    def _generate_configuration_steps(self, analysis) -> str:
        """Generate configuration steps."""
        return """### 1. Create configuration file

```bash
cp config.example.yml config.yml
```

### 2. Set environment variables

```bash
export DATABASE_URL="postgresql://localhost/dbname"
export API_KEY="your-api-key"
export LOG_LEVEL="INFO"
```

Or create a `.env` file:

```
DATABASE_URL=postgresql://localhost/dbname
API_KEY=your-api-key
LOG_LEVEL=INFO
```

### 3. Initialize database (if applicable)

```bash
python manage.py migrate
# or
npm run migrate
```"""
    
    def _generate_run_steps(self, analysis, primary_lang: str) -> str:
        """Generate run steps."""
        if "Python" in primary_lang:
            return """### Development Mode

```bash
python main.py
# or
python -m uvicorn app:app --reload
```

### Production Mode

```bash
python main.py --production
# or
gunicorn app:app --workers 4
```

### Using Docker

```bash
docker-compose up
```"""
        elif "JavaScript" in primary_lang or "TypeScript" in primary_lang:
            return """### Development Mode

```bash
npm run dev
# or
yarn dev
```

### Production Mode

```bash
npm start
# or
yarn start
```

### Using Docker

```bash
docker-compose up
```"""
        else:
            return """### Run the application

```bash
# See project README for specific commands
```

### Using Docker

```bash
docker-compose up
```"""
    
    def _generate_verification_steps(self, analysis) -> str:
        """Generate verification steps."""
        has_api = self._has_api_services(analysis)
        
        if has_api:
            return """### Check health endpoint

```bash
curl http://localhost:8000/health
```

Expected response:
```json
{
  "status": "healthy",
  "timestamp": "2025-10-21T00:00:00Z"
}
```

### Access API documentation

Open `http://localhost:8000/docs` in your browser."""
        else:
            return """### Check application status

```bash
# Run health check command
# See project documentation for specific commands
```"""
    
    def _generate_basic_usage(self, analysis, primary_lang: str) -> str:
        """Generate basic usage examples."""
        if "Python" in primary_lang:
            return """### Python Example

```python
from app import create_app

# Create application instance
app = create_app()

# Run the application
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
```"""
        elif "JavaScript" in primary_lang or "TypeScript" in primary_lang:
            return """### JavaScript Example

```javascript
const app = require('./app');

// Start the application
app.listen(8000, () => {
    console.log('Application running on port 8000');
});
```"""
        else:
            return """See project documentation for language-specific examples."""
    
    def _generate_api_examples(self, analysis) -> str:
        """Generate API usage examples."""
        return """## API Usage

### Making API Requests

#### Python

```python
import requests

# Get resources
response = requests.get(
    "http://localhost:8000/api/v1/resources",
    headers={"Authorization": "Bearer YOUR_TOKEN"}
)

resources = response.json()
print(resources)
```

#### JavaScript

```javascript
const response = await fetch('http://localhost:8000/api/v1/resources', {
    headers: {
        'Authorization': 'Bearer YOUR_TOKEN'
    }
});

const resources = await response.json();
console.log(resources);
```

#### cURL

```bash
curl -X GET "http://localhost:8000/api/v1/resources" \\
  -H "Authorization: Bearer YOUR_TOKEN"
```

### Creating Resources

#### Python

```python
response = requests.post(
    "http://localhost:8000/api/v1/resources",
    headers={"Authorization": "Bearer YOUR_TOKEN"},
    json={"name": "New Resource", "description": "Description"}
)

new_resource = response.json()
```

#### JavaScript

```javascript
const response = await fetch('http://localhost:8000/api/v1/resources', {
    method: 'POST',
    headers: {
        'Authorization': 'Bearer YOUR_TOKEN',
        'Content-Type': 'application/json'
    },
    body: JSON.stringify({
        name: 'New Resource',
        description: 'Description'
    })
});

const newResource = await response.json();
```
"""
    
    def _generate_advanced_usage(self, analysis, primary_lang: str) -> str:
        """Generate advanced usage examples."""
        return """### Batch Operations

```python
# Process multiple items
items = ['item1', 'item2', 'item3']
results = []

for item in items:
    result = process_item(item)
    results.append(result)
```

### Error Handling

```python
try:
    result = api_call()
except APIError as e:
    logger.error(f"API call failed: {e}")
    # Handle error
except Exception as e:
    logger.error(f"Unexpected error: {e}")
    # Handle unexpected errors
```

### Async Operations

```python
import asyncio

async def process_async():
    tasks = [process_item(i) for i in range(10)]
    results = await asyncio.gather(*tasks)
    return results
```"""
    
    def _generate_code_samples(self, analysis, primary_lang: str) -> str:
        """Generate code samples."""
        return """### Complete Example

```python
import os
from app import create_app
from config import load_config

# Load configuration
config = load_config()

# Create app
app = create_app(config)

# Setup logging
import logging
logging.basicConfig(level=config.log_level)
logger = logging.getLogger(__name__)

# Main entry point
if __name__ == "__main__":
    logger.info("Starting application...")
    app.run(
        host=config.host,
        port=config.port,
        debug=config.debug
    )
```"""
    
    def _generate_testing_examples(self, analysis, primary_lang: str) -> str:
        """Generate testing examples."""
        if "Python" in primary_lang:
            return """### Unit Tests

```python
import pytest
from app import process_item

def test_process_item():
    result = process_item("test")
    assert result is not None
    assert result.status == "success"

def test_process_item_error():
    with pytest.raises(ValueError):
        process_item(None)
```

### Integration Tests

```python
def test_api_endpoint(client):
    response = client.get("/api/v1/resources")
    assert response.status_code == 200
    assert "data" in response.json()
```

### Run Tests

```bash
pytest tests/
# With coverage
pytest --cov=app tests/
```"""
        else:
            return """See project documentation for testing examples."""
    
    def _describe_integration_methods(self, analysis) -> str:
        """Describe integration methods."""
        has_api = self._has_api_services(analysis)
        
        if has_api:
            return """### REST API

Primary integration method via HTTP REST API.

### SDKs

Official SDKs available for popular languages.

### Webhooks

Event-driven integration via webhooks."""
        else:
            return """### Library Import

Import as a library in your application.

### CLI Integration

Use command-line interface for scripting."""
    
    def _generate_auth_setup(self, analysis) -> str:
        """Generate authentication setup."""
        return """### Obtain API Credentials

1. Register an account
2. Generate API key from dashboard
3. Store securely in environment variables

```bash
export API_KEY="your-api-key-here"
```

### Authenticate Requests

```python
import requests

headers = {
    "Authorization": f"Bearer {os.environ['API_KEY']}"
}

response = requests.get(url, headers=headers)
```"""
    
    def _generate_sdk_usage(self, analysis) -> str:
        """Generate SDK usage."""
        return """### Install SDK

```bash
pip install ecosystem-sdk
```

### Use SDK

```python
from ecosystem_sdk import Client

client = Client(api_key=os.environ['API_KEY'])
resources = client.resources.list()
```"""
    
    def _generate_webhook_integration(self, analysis) -> str:
        """Generate webhook integration."""
        return """### Setup Webhook Endpoint

```python
from flask import Flask, request

app = Flask(__name__)

@app.route('/webhook', methods=['POST'])
def handle_webhook():
    data = request.json
    # Process webhook data
    return {'status': 'received'}, 200
```

### Register Webhook

```bash
curl -X POST "http://api.example.com/webhooks" \\
  -H "Authorization: Bearer YOUR_TOKEN" \\
  -d '{"url": "https://your-domain.com/webhook"}'
```"""
    
    def _generate_integration_error_handling(self) -> str:
        """Generate integration error handling."""
        return """### Retry Logic

```python
from time import sleep

def call_with_retry(func, max_retries=3):
    for attempt in range(max_retries):
        try:
            return func()
        except APIError as e:
            if attempt == max_retries - 1:
                raise
            sleep(2 ** attempt)  # Exponential backoff
```

### Error Logging

```python
import logging

logger = logging.getLogger(__name__)

try:
    result = api_call()
except Exception as e:
    logger.error(f"Integration failed: {e}", exc_info=True)
```"""
    
    def _generate_integration_best_practices(self) -> str:
        """Generate integration best practices."""
        return """- Use environment variables for credentials
- Implement retry logic with exponential backoff
- Log all integration attempts
- Validate responses before processing
- Handle rate limiting gracefully
- Monitor integration health"""
    
    def _generate_setup_workflow(self, analysis) -> str:
        """Generate setup workflow."""
        return """1. Install prerequisites
2. Clone repository
3. Install dependencies
4. Configure environment
5. Initialize database
6. Run application
7. Verify installation"""
    
    def _generate_processing_workflow(self, analysis) -> str:
        """Generate processing workflow."""
        return """1. Load input data
2. Validate data format
3. Process each item
4. Handle errors
5. Store results
6. Generate reports"""
    
    def _generate_api_workflow(self, analysis) -> str:
        """Generate API workflow."""
        return """1. Obtain API credentials
2. Authenticate request
3. Make API call
4. Handle response
5. Process data
6. Handle errors"""
    
    def _generate_deployment_workflow(self, analysis) -> str:
        """Generate deployment workflow."""
        return """1. Build application
2. Run tests
3. Build Docker image
4. Push to registry
5. Deploy to environment
6. Verify deployment
7. Monitor health"""
    
    def _generate_monitoring_workflow(self, analysis) -> str:
        """Generate monitoring workflow."""
        return """1. Check application logs
2. Review error rates
3. Monitor performance metrics
4. Check resource usage
5. Review alerts
6. Debug issues
7. Apply fixes"""

