# Individual Docker Compose for Frontend Service
# This allows the frontend to run independently as a standalone service

version: "3.9"

services:
  frontend:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ../../:/app:ro
      - ../../config.yml:/app/config.yml:ro
      - ../shared/config.yaml:/app/services/shared/config.yaml:ro
      - ./config.yaml:/app/services/frontend/config.yaml:ro
    environment:
      - ENVIRONMENT=development
    command: bash -lc "pip install --no-cache-dir fastapi uvicorn httpx pydantic && python services/frontend/main.py"
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
