#!/usr/bin/env python3
"""
Docker Compose Generator

Generates docker-compose.yml from service_registry.yaml to ensure
complete consistency and eliminate configuration drift.

✅ PHASE 2: Automated docker-compose generation from registry
Eliminates all port conflicts, service name mismatches, and configuration drift.

Usage:
    python scripts/generate_compose.py
    python scripts/generate_compose.py --output docker-compose.generated.yml
"""

import sys
import argparse
from pathlib import Path
from datetime import datetime

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from config.registry import get_registry


COMPOSE_TEMPLATE = """# =========================================================================
# DOCKER COMPOSE - AUTO-GENERATED FROM SERVICE REGISTRY
# =========================================================================
# Generated: {timestamp}
# Registry Version: {registry_version}
# 
# ⚠️  WARNING: Do NOT edit this file manually!
# This file is auto-generated from config/service_registry.yaml
# 
# To make changes:
# 1. Edit config/service_registry.yaml
# 2. Run: python scripts/generate_compose.py
# 3. Review the generated file
# 4. Commit both files together
# 
# ✅ PHASE 2: This prevents all configuration drift and port conflicts
# =========================================================================

version: '{compose_version}'

services:
  # ========================================================================
  # INFRASTRUCTURE SERVICES
  # ========================================================================
  
  # PostgreSQL Database
  postgres:
    image: {postgres_image}
    container_name: {postgres_container}
    environment:
      POSTGRES_DB: {db_name}
      POSTGRES_USER: {db_user}
      POSTGRES_PASSWORD: {db_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "{postgres_port}:{postgres_port}"
    volumes:
      - {postgres_volume}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {db_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - {network}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis (Queue & Cache)
  redis:
    image: {redis_image}
    container_name: {redis_container}
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "{redis_port}:{redis_port}"
    volumes:
      - {redis_volume}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - {network}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Ollama (Local LLM)
  ollama:
    image: {ollama_image}
    container_name: {ollama_container}
    ports:
      - "{ollama_port}:{ollama_port}"
    volumes:
      - {ollama_volume}
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_CTX=2048
      - OLLAMA_NUM_THREADS=10
      - OLLAMA_NUM_BATCH=2048
      - OLLAMA_KEEP_ALIVE=10m
      - OLLAMA_FLASH_ATTENTION=true
      - OLLAMA_MAX_QUEUE=10
      - OLLAMA_NUM_PARALLEL=2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:{ollama_port}/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - {network}
    restart: unless-stopped

  # ========================================================================
  # APPLICATION SERVICES
  # ========================================================================

  # Embedding Service (FastEmbed)
  embedding-service:
    build:
      context: ../ecosystem-mcp-embedding
      dockerfile: Dockerfile
    image: {embedding_image}
    container_name: {embedding_container}
    ports:
      - "{embedding_port}:{embedding_internal_port}"
    volumes:
      - {embedding_models_volume}
    environment:
      - MODEL_NAME=BAAI/bge-base-en-v1.5
      - CACHE_DIR=/app/models
      - MAX_BATCH_SIZE=32
      - DEVICE=cpu
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:{embedding_internal_port}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - {network}
    restart: unless-stopped
    depends_on:
      - redis
      - postgres

  # Main API Service
  ecosystem-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: {api_image}
    container_name: {api_container}
    ports:
      - "{api_port}:{api_port}"
      - "{metrics_port}:{metrics_port}"
    volumes:
      - {chroma_volume}
      - {backups_volume}
      - /Users/mykalthomas/Documents/work/Hackathon:/workspace:ro
    environment:
      - DATABASE_URL=postgresql://{db_user}:{db_password}@postgres:{postgres_port}/{db_name}
      - REDIS_URL=redis://redis:{redis_port}/0
      - OLLAMA_BASE_URL=http://ollama:{ollama_port}
      - EMBEDDING_SERVICE_URL=http://embedding-service:{embedding_internal_port}
      - CHROMA_PATH=/app/data/chroma_db
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:{api_port}/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - {network}
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - ollama
      - embedding-service

  # Dashboard (Streamlit)
  dashboard:
    build:
      context: ../ecosystem-mcp-dashboard
      dockerfile: Dockerfile
    image: {dashboard_image}
    container_name: {dashboard_container}
    ports:
      - "{dashboard_port}:{dashboard_port}"
    environment:
      - ECOSYSTEM_MCP_URL=http://ecosystem-mcp:{api_port}
      - STREAMLIT_SERVER_PORT={dashboard_port}
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:{dashboard_port}/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - {network}
    restart: unless-stopped
    depends_on:
      - ecosystem-mcp

# =========================================================================
# NETWORKS
# =========================================================================
networks:
  {network}:
    driver: bridge

# =========================================================================
# METADATA
# =========================================================================
# Generated from: config/service_registry.yaml v{registry_version}
# Generated at: {timestamp}
# Generator: scripts/generate_compose.py
# Registry environment: {environment}
# 
# Benefits of generated compose:
# ✅ Zero configuration drift
# ✅ Port conflicts impossible
# ✅ Service names always consistent
# ✅ Single source of truth (registry)
# ✅ Easy to regenerate after changes
# =========================================================================
"""


def generate_compose(output_path: Path = None) -> str:
    """
    Generate docker-compose.yml from service registry.
    
    Args:
        output_path: Where to write the generated file (default: docker-compose.yml)
    
    Returns:
        Generated compose content
    """
    print("🔍 Loading service registry...")
    registry = get_registry()
    
    print(f"✅ Registry loaded: v{registry.version} (environment: {registry.environment})")
    
    # Extract configuration values from registry
    config = {
        'timestamp': datetime.utcnow().isoformat() + 'Z',
        'registry_version': registry.version,
        'environment': registry.environment,
        'compose_version': registry.docker.get('version', '3.8') if registry.docker else '3.8',
        
        # Network
        'network': registry.services.ecosystem_mcp.network,
        
        # PostgreSQL
        'postgres_image': registry.services.postgres.image,
        'postgres_container': registry.services.postgres.container_name,
        'postgres_port': registry.services.postgres.ports.main,
        'postgres_volume': './data/postgresql:/var/lib/postgresql/data',
        'db_name': registry.database.connection.database,
        'db_user': registry.database.connection.user,
        'db_password': registry.database.connection.password,
        
        # Redis
        'redis_image': registry.services.redis.image,
        'redis_container': registry.services.redis.container_name,
        'redis_port': registry.services.redis.ports.main,
        'redis_volume': './data/redis:/data',
        
        # Ollama
        'ollama_image': registry.services.ollama.image,
        'ollama_container': registry.services.ollama.container_name,
        'ollama_port': registry.services.ollama.ports.api,
        'ollama_volume': './data/ollama:/root/.ollama',
        
        # Embedding Service
        'embedding_image': 'ecosystem-mcp-embedding:latest',
        'embedding_container': registry.services.ecosystem_mcp_embedding.container_name,
        'embedding_port': registry.services.ecosystem_mcp_embedding.ports.api,
        'embedding_internal_port': registry.services.ecosystem_mcp_embedding.ports.internal,
        'embedding_models_volume': './data/embedding_models:/app/models',
        
        # Main API
        'api_image': 'ecosystem-mcp:latest',
        'api_container': registry.services.ecosystem_mcp.container_name,
        'api_port': registry.services.ecosystem_mcp.ports.api,
        'metrics_port': registry.services.ecosystem_mcp.ports.metrics,
        'chroma_volume': './data/chroma_db:/app/data/chroma_db',
        'backups_volume': './data/backups:/app/backups',
        
        # Dashboard
        'dashboard_image': 'ecosystem-mcp-dashboard:latest',
        'dashboard_container': registry.services.ecosystem_mcp_dashboard.container_name,
        'dashboard_port': registry.services.ecosystem_mcp_dashboard.ports.ui,
    }
    
    print(f"\n📋 Configuration extracted:")
    print(f"   Network: {config['network']}")
    print(f"   PostgreSQL port: {config['postgres_port']}")
    print(f"   Redis port: {config['redis_port']}")
    print(f"   Ollama port: {config['ollama_port']}")
    print(f"   API port: {config['api_port']}")
    print(f"   Embedding port: {config['embedding_port']}")
    print(f"   Dashboard port: {config['dashboard_port']}")
    
    # Generate compose file
    compose_content = COMPOSE_TEMPLATE.format(**config)
    
    # Write to file
    if output_path is None:
        output_path = Path(__file__).parent.parent / "docker-compose.generated.yml"
    
    output_path = Path(output_path)
    output_path.write_text(compose_content)
    
    print(f"\n✅ Docker compose generated: {output_path}")
    print(f"   Size: {len(compose_content)} bytes")
    print(f"   Lines: {len(compose_content.splitlines())}")
    
    print(f"\n🎯 Next steps:")
    print(f"   1. Review the generated file: {output_path}")
    print(f"   2. Compare with existing docker-compose.yml")
    print(f"   3. Test with: docker-compose -f {output_path.name} config")
    print(f"   4. Deploy with: docker-compose -f {output_path.name} up -d")
    
    return compose_content


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate docker-compose.yml from service registry"
    )
    parser.add_argument(
        '--output', '-o',
        type=Path,
        default=None,
        help="Output file path (default: docker-compose.generated.yml)"
    )
    parser.add_argument(
        '--replace', '-r',
        action='store_true',
        help="Replace existing docker-compose.yml (use with caution!)"
    )
    
    args = parser.parse_args()
    
    if args.replace:
        output_path = Path(__file__).parent.parent / "docker-compose.yml"
        print("⚠️  WARNING: This will replace docker-compose.yml!")
        response = input("Are you sure? (yes/no): ")
        if response.lower() != 'yes':
            print("❌ Aborted")
            return 1
    else:
        output_path = args.output
    
    try:
        generate_compose(output_path)
        print("\n🎉 Docker compose generation complete!")
        return 0
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())


