"""
Workflow Tests for --help

Generated: 2025-10-09T10:48:56.318814
Auto-generated by: generate_workflow_tests.py

These tests verify end-to-end workflows for the --help service,
including single-service workflows, multi-service integrations, and
version compatibility.
"""

import pytest
import asyncio
from typing import Dict, Any
from httpx import AsyncClient

pytestmark = pytest.mark.workflow


@pytest.fixture
async def service_client(workflow_context):
    """Get HTTP client for --help"""
    return workflow_context.get_client("--help", "v2")


@pytest.fixture
async def v1_client(workflow_context):
    """Get HTTP client for --help v1"""
    return workflow_context.get_client("--help", "v1")


@pytest.mark.asyncio
class TestHelpWorkflows:
    """
    Workflow tests for --help
    
    Tests both v1 (legacy) and v2 (refactored) implementations.
    """
    
    # Test data
    SAMPLE_DATA = {
        "title": "Test Resource",
        "description": "This is test data for workflow testing"
    }
    
    @pytest.mark.critical
    async def test_create_retrieve_workflow(self, workflow_context):
        """
        Create resource and retrieve it
        
        Type: single_service
        Steps:
        1. Create resource via POST
        2. Retrieve resource via GET
        3. Verify data matches
        """
        # Step 1: Create resource
        client = workflow_context.get_client("{self.service_name}")
        create_response = await client.post(
            "/resources",
            json=self.SAMPLE_DATA
        )
        assert create_response.status_code == 201
        
        resource_id = create_response.json()["data"]["id"]
        
        # Register cleanup
        workflow_context.register_cleanup(
            lambda: client.delete(f"/resources/{resource_id}")
        )
        
        # Step 2: Retrieve resource
        get_response = await client.get(f"/resources/{resource_id}")
        assert get_response.status_code == 200
        
        # Step 3: Verify data
        resource_data = get_response.json()["data"]
        assert resource_data["title"] == self.SAMPLE_DATA["title"]


    @pytest.mark.critical
    async def test_full_crud_workflow(self, workflow_context):
        """
        Complete CRUD lifecycle
        
        Type: single_service
        Steps:
        1. Create resource
        2. Read resource
        3. Update resource
        4. Delete resource
        5. Verify deletion
        """
        # Step 1: Create resource
        client = workflow_context.get_client("{self.service_name}")
        create_response = await client.post(
            "/resources",
            json=self.SAMPLE_DATA
        )
        assert create_response.status_code == 201
        
        resource_id = create_response.json()["data"]["id"]
        
        # Register cleanup
        workflow_context.register_cleanup(
            lambda: client.delete(f"/resources/{resource_id}")
        )
        
        # Step 2: Retrieve resource
        get_response = await client.get(f"/resources/{resource_id}")
        assert get_response.status_code == 200
        
        # Step 3: Verify data
        resource_data = get_response.json()["data"]
        assert resource_data["title"] == self.SAMPLE_DATA["title"]


    @pytest.mark.compatibility
    async def test_v1_to_v2_compatibility(self, workflow_context):
        """
        Test v1 client with v2 backend
        
        Type: compatibility
        Steps:
        1. Create via v1 API
        2. Process via v2 API
        3. Retrieve via v1 API
        4. Verify compatibility
        """
        # Step 1: Create via v1
        v1_client = workflow_context.get_client("{self.service_name}", "v1")
        v1_response = await v1_client.post("/resources", json=self.SAMPLE_DATA)
        resource_id = v1_response.json()["id"]
        
        # Step 2: Process via v2
        v2_client = workflow_context.get_client("{self.service_name}", "v2")
        v2_response = await v2_client.post(
            "/process",
            json={"resource_id": resource_id}
        )
        assert v2_response.status_code == 200
        
        # Step 3: Retrieve via v1
        retrieve_response = await v1_client.get(f"/resources/{resource_id}")
        assert retrieve_response.status_code == 200
        
        # Step 4: Verify v1 can see v2 changes
        data = retrieve_response.json()
        assert "processed" in data
        assert data["processed"] is True
        
        # Step 5: Verify deprecation headers
        assert "X-API-Deprecation" in retrieve_response.headers


    @pytest.mark.compatibility
    async def test_v2_to_v1_compatibility(self, workflow_context):
        """
        Test v2 client with v1 backend
        
        Type: compatibility
        Steps:
        1. Create via v2 API
        2. Process via v1 API
        3. Retrieve via v2 API
        4. Verify compatibility
        """
        # Step 1: Create via v1
        v1_client = workflow_context.get_client("{self.service_name}", "v1")
        v1_response = await v1_client.post("/resources", json=self.SAMPLE_DATA)
        resource_id = v1_response.json()["id"]
        
        # Step 2: Process via v2
        v2_client = workflow_context.get_client("{self.service_name}", "v2")
        v2_response = await v2_client.post(
            "/process",
            json={"resource_id": resource_id}
        )
        assert v2_response.status_code == 200
        
        # Step 3: Retrieve via v1
        retrieve_response = await v1_client.get(f"/resources/{resource_id}")
        assert retrieve_response.status_code == 200
        
        # Step 4: Verify v1 can see v2 changes
        data = retrieve_response.json()
        assert "processed" in data
        assert data["processed"] is True
        
        # Step 5: Verify deprecation headers
        assert "X-API-Deprecation" in retrieve_response.headers


    # Helper methods
    
    async def _wait_for_job_completion(
        self,
        client: AsyncClient,
        job_id: str,
        timeout: int = 30
    ):
        """Wait for job to complete"""
        for _ in range(timeout):
            response = await client.get(f"/jobs/{job_id}")
            status = response.json()["data"]["status"]
            
            if status == "completed":
                return
            elif status == "failed":
                raise AssertionError("Job failed")
            
            await asyncio.sleep(1)
        
        raise AssertionError(f"Job did not complete within {timeout} seconds")
    
    async def _cleanup_resource(self, client: AsyncClient, resource_id: str):
        """Clean up test resource"""
        try:
            await client.delete(f"/resources/{resource_id}")
        except Exception as e:
            print(f"Warning: Could not clean up resource {resource_id}: {e}")
