# Prompt-store-specific configuration
# Inherits from shared base_config.yaml

# Override server port for prompt-store
server:
  port: 5110

# Prompt-store specific database settings
database:
  path: ${PROMPT_STORE_DB:-/app/data/prompt_store.db}
  redis_url: ${REDIS_URL:-redis://redis:6379}

# Prompt store settings
prompt_store:
  # Default database path fallback
  default_db_path: ${DEFAULT_DB_PATH:-prompt_store.db}
