version: "3.9"

services:
  # Redis - Required dependency
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # LLM Gateway - Required for mock data generation
  llm-gateway:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ../../:/app:ro
      - llm_gateway_cache:/app/cache
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - ENVIRONMENT=development
      - OLLAMA_ENDPOINT=http://host.docker.internal:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    command: bash -c "pip install --no-cache-dir fastapi uvicorn httpx pydantic redis aioredis && python services/llm-gateway/main.py"
    ports:
      - "5055:5055"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5055/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Mock Data Generator - Main service
  mock-data-generator:
    build:
      context: ../..
      dockerfile: services/mock-data-generator/Dockerfile
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - ENVIRONMENT=development
      - LLM_GATEWAY_URL=http://llm-gateway:5055
      - DOC_STORE_URL=http://host.docker.internal:5087
    ports:
      - "5065:5065"
    depends_on:
      llm-gateway:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5065/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
  llm_gateway_cache:
    driver: local

networks:
  default:
    name: mock-data-generator-network
    driver: bridge
