# Doc-store-specific configuration
# Inherits from shared base_config.yaml

# Override server port for doc-store
server:
  port: 5087

# Doc-store specific database settings
database:
  path: ${DOCSTORE_DB:-services/doc-store/db.sqlite3}
  connection_pool_size: ${DOCSTORE_CONNECTION_POOL_SIZE:-5}

# Testing configuration
testing: ${TESTING:-false}
